[2023-02-27T15:17:29.640+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: update-filter.gcs_sensor manual__2023-02-27T15:17:28.618161+00:00 [queued]>
[2023-02-27T15:17:29.645+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: update-filter.gcs_sensor manual__2023-02-27T15:17:28.618161+00:00 [queued]>
[2023-02-27T15:17:29.646+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-27T15:17:29.646+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-02-27T15:17:29.647+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-27T15:17:29.654+0000] {taskinstance.py:1300} INFO - Executing <Task(GCSObjectExistenceSensor): gcs_sensor> on 2023-02-27 15:17:28.618161+00:00
[2023-02-27T15:17:29.659+0000] {standard_task_runner.py:55} INFO - Started process 918 to run task
[2023-02-27T15:17:29.662+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'update-filter', 'gcs_sensor', 'manual__2023-02-27T15:17:28.618161+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/update-filter.py', '--cfg-path', '/tmp/tmp645gpy7q']
[2023-02-27T15:17:29.663+0000] {standard_task_runner.py:83} INFO - Job 26: Subtask gcs_sensor
[2023-02-27T15:17:29.712+0000] {task_command.py:388} INFO - Running <TaskInstance: update-filter.gcs_sensor manual__2023-02-27T15:17:28.618161+00:00 [running]> on host d766c014b21e
[2023-02-27T15:17:29.767+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=update-filter
AIRFLOW_CTX_TASK_ID=gcs_sensor
AIRFLOW_CTX_EXECUTION_DATE=2023-02-27T15:17:28.618161+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-27T15:17:28.618161+00:00
[2023-02-27T15:17:29.771+0000] {gcs.py:89} INFO - Sensor checks existence of : ***-gcs-bq, update.csv
[2023-02-27T15:17:29.780+0000] {base.py:73} INFO - Using connection ID '***-gcs-bq' for task execution.
[2023-02-27T15:17:29.790+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 199, in execute
    poke_return = self.poke(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/sensors/gcs.py", line 95, in poke
    return hook.exists(self.bucket, self.object, self.retry)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 550, in exists
    client = self.get_conn()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 157, in get_conn
    credentials=self.get_credentials(), client_info=CLIENT_INFO, project=self.project_id
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 275, in get_credentials
    credentials, _ = self.get_credentials_and_project_id()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 261, in get_credentials_and_project_id
    delegates=delegates,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/utils/credentials_provider.py", line 332, in get_credentials_and_project_id
    return _CredentialProvider(*args, **kwargs).get_credentials_and_project()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/utils/credentials_provider.py", line 211, in __init__
    "The `keyfile_dict`, `key_path`, and `key_secret_name` fields "
airflow.exceptions.AirflowException: The `keyfile_dict`, `key_path`, and `key_secret_name` fields are all mutually exclusive. Please provide only one value.
[2023-02-27T15:17:29.792+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=update-filter, task_id=gcs_sensor, execution_date=20230227T151728, start_date=20230227T151729, end_date=20230227T151729
[2023-02-27T15:17:29.799+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 26 for task gcs_sensor (The `keyfile_dict`, `key_path`, and `key_secret_name` fields are all mutually exclusive. Please provide only one value.; 918)
[2023-02-27T15:17:29.833+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-02-27T15:17:29.853+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
