[2023-02-24T22:04:45.820+0000] {processor.py:153} INFO - Started process (PID=34) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:04:45.830+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:04:45.832+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:04:45.832+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:04:46.227+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:04:46.222+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageCheckOperator
ImportError: cannot import name 'GoogleCloudStorageCheckOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-02-24T22:04:46.227+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:04:46.241+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.439 seconds
[2023-02-24T22:05:16.747+0000] {processor.py:153} INFO - Started process (PID=114) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:05:16.749+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:05:16.750+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:05:16.750+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:05:16.874+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:05:16.872+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageCheckOperator
ImportError: cannot import name 'GoogleCloudStorageCheckOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-02-24T22:05:16.874+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:05:16.887+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.146 seconds
[2023-02-24T22:05:47.859+0000] {processor.py:153} INFO - Started process (PID=194) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:05:47.860+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:05:47.861+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:05:47.861+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:05:48.114+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:05:48.111+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageCheckOperator
ImportError: cannot import name 'GoogleCloudStorageCheckOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-02-24T22:05:48.115+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:05:48.127+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.270 seconds
[2023-02-24T22:06:18.851+0000] {processor.py:153} INFO - Started process (PID=260) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:06:18.854+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:06:18.856+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:06:18.855+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:06:19.060+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:06:19.059+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageCheckOperator
ImportError: cannot import name 'GoogleCloudStorageCheckOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-02-24T22:06:19.061+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:06:19.072+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.226 seconds
[2023-02-24T22:06:49.933+0000] {processor.py:153} INFO - Started process (PID=339) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:06:49.935+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:06:49.937+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:06:49.936+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:06:50.135+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:06:50.134+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageCheckOperator
ImportError: cannot import name 'GoogleCloudStorageCheckOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-02-24T22:06:50.136+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:06:50.147+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.219 seconds
[2023-02-24T22:07:13.758+0000] {processor.py:153} INFO - Started process (PID=406) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:07:13.761+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:07:13.763+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:07:13.762+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:07:13.978+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:07:13.977+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GCSDownloadOperator
ImportError: cannot import name 'GCSDownloadOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-02-24T22:07:13.979+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:07:13.992+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.240 seconds
[2023-02-24T22:07:44.842+0000] {processor.py:153} INFO - Started process (PID=485) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:07:44.845+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:07:44.847+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:07:44.847+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:07:45.042+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:07:45.040+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GCSDownloadOperator
ImportError: cannot import name 'GCSDownloadOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-02-24T22:07:45.042+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:07:45.053+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.216 seconds
[2023-02-24T22:08:15.680+0000] {processor.py:153} INFO - Started process (PID=564) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:08:15.683+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:08:15.685+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:08:15.684+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:08:15.892+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:08:15.890+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GCSDownloadOperator
ImportError: cannot import name 'GCSDownloadOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-02-24T22:08:15.892+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:08:15.904+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.229 seconds
[2023-02-24T22:08:46.869+0000] {processor.py:153} INFO - Started process (PID=643) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:08:46.871+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:08:46.872+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:08:46.872+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:08:47.091+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:08:47.089+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GCSDownloadOperator
ImportError: cannot import name 'GCSDownloadOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-02-24T22:08:47.092+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:08:47.104+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.237 seconds
[2023-02-24T22:08:55.802+0000] {processor.py:153} INFO - Started process (PID=683) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:08:55.804+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:08:55.806+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:08:55.805+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:08:56.008+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:08:56.007+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageCheckOperator
ImportError: cannot import name 'GoogleCloudStorageCheckOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-02-24T22:08:56.009+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:08:56.020+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.222 seconds
[2023-02-24T22:09:26.696+0000] {processor.py:153} INFO - Started process (PID=762) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:09:26.697+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:09:26.698+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:09:26.698+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:09:26.883+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:09:26.882+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageCheckOperator
ImportError: cannot import name 'GoogleCloudStorageCheckOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-02-24T22:09:26.884+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:09:26.896+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.202 seconds
[2023-02-24T22:09:27.745+0000] {processor.py:153} INFO - Started process (PID=763) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:09:27.747+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:09:27.749+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:09:27.749+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:09:27.960+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:09:27.959+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageObjectExistenceSensor
ImportError: cannot import name 'GoogleCloudStorageObjectExistenceSensor' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-02-24T22:09:27.962+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:09:27.975+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.237 seconds
[2023-02-24T22:09:58.869+0000] {processor.py:153} INFO - Started process (PID=841) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:09:58.873+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:09:58.875+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:09:58.874+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:09:59.067+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:09:59.066+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageObjectExistenceSensor
ImportError: cannot import name 'GoogleCloudStorageObjectExistenceSensor' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-02-24T22:09:59.068+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:09:59.079+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.215 seconds
[2023-02-24T22:10:29.978+0000] {processor.py:153} INFO - Started process (PID=920) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:10:29.980+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:10:29.982+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:10:29.982+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:10:30.186+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:10:30.185+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageObjectExistenceSensor
ImportError: cannot import name 'GoogleCloudStorageObjectExistenceSensor' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-02-24T22:10:30.187+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:10:30.198+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.226 seconds
[2023-02-24T22:11:00.333+0000] {processor.py:153} INFO - Started process (PID=986) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:11:00.335+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:11:00.337+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:11:00.337+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:11:00.533+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:11:00.532+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageObjectExistenceSensor
ImportError: cannot import name 'GoogleCloudStorageObjectExistenceSensor' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-02-24T22:11:00.534+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:11:00.545+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.217 seconds
[2023-02-24T22:11:30.631+0000] {processor.py:153} INFO - Started process (PID=1064) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:11:30.634+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:11:30.635+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:11:30.635+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:11:30.828+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:11:30.827+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageObjectExistenceSensor
ImportError: cannot import name 'GoogleCloudStorageObjectExistenceSensor' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-02-24T22:11:30.830+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:11:30.842+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.216 seconds
[2023-02-24T22:12:01.780+0000] {processor.py:153} INFO - Started process (PID=1143) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:12:01.783+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:12:01.784+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:12:01.784+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:12:02.006+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:12:02.004+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageObjectExistenceSensor
ImportError: cannot import name 'GoogleCloudStorageObjectExistenceSensor' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-02-24T22:12:02.006+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:12:02.018+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.242 seconds
[2023-02-24T22:12:25.427+0000] {processor.py:153} INFO - Started process (PID=1201) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:12:25.430+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:12:25.431+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:12:25.431+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:12:25.632+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:12:25.631+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageObjectExistenceSensor
ImportError: cannot import name 'GoogleCloudStorageObjectExistenceSensor' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-02-24T22:12:25.633+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:12:25.643+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.222 seconds
[2023-02-24T22:12:55.922+0000] {processor.py:153} INFO - Started process (PID=1280) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:12:55.923+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:12:55.924+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:12:55.924+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:12:56.130+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:12:56.128+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageObjectExistenceSensor
ImportError: cannot import name 'GoogleCloudStorageObjectExistenceSensor' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-02-24T22:12:56.132+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:12:56.144+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.225 seconds
[2023-02-24T22:13:26.179+0000] {processor.py:153} INFO - Started process (PID=1348) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:13:26.180+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:13:26.181+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:13:26.180+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:13:26.379+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:13:26.378+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageObjectExistenceSensor
ImportError: cannot import name 'GoogleCloudStorageObjectExistenceSensor' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-02-24T22:13:26.380+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:13:26.392+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.216 seconds
[2023-02-24T22:13:57.356+0000] {processor.py:153} INFO - Started process (PID=1428) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:13:57.359+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:13:57.361+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:13:57.361+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:13:57.560+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:13:57.559+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageObjectExistenceSensor
ImportError: cannot import name 'GoogleCloudStorageObjectExistenceSensor' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-02-24T22:13:57.560+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:13:57.571+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.222 seconds
[2023-02-24T22:14:28.293+0000] {processor.py:153} INFO - Started process (PID=1507) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:14:28.295+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:14:28.297+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:14:28.297+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:14:28.502+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:14:28.500+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageObjectExistenceSensor
ImportError: cannot import name 'GoogleCloudStorageObjectExistenceSensor' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-02-24T22:14:28.502+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:14:28.514+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.226 seconds
[2023-02-24T22:14:56.841+0000] {processor.py:153} INFO - Started process (PID=1571) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:14:56.842+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:14:56.843+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:14:56.843+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:14:57.046+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:14:57.043+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageObjectExistenceSensor
ImportError: cannot import name 'GoogleCloudStorageObjectExistenceSensor' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-02-24T22:14:57.048+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:14:57.064+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.225 seconds
[2023-02-24T22:15:27.119+0000] {processor.py:153} INFO - Started process (PID=1643) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:15:27.120+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:15:27.120+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:15:27.120+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:15:27.350+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:15:27.348+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageObjectExistenceSensor
ImportError: cannot import name 'GoogleCloudStorageObjectExistenceSensor' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-02-24T22:15:27.351+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:15:27.362+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.246 seconds
[2023-02-24T22:15:30.956+0000] {processor.py:153} INFO - Started process (PID=1667) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:15:30.957+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:15:30.958+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:15:30.958+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:15:31.205+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:15:31.201+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 4, in <module>
    from airflow.providers.google.cloud.operators.gcs import GCSDownloadBucketOperator
ImportError: cannot import name 'GCSDownloadBucketOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-02-24T22:15:31.206+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:15:31.226+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.272 seconds
[2023-02-24T22:16:02.071+0000] {processor.py:153} INFO - Started process (PID=1736) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:16:02.073+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:16:02.075+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:16:02.074+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:16:02.279+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:16:02.278+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 4, in <module>
    from airflow.providers.google.cloud.operators.gcs import GCSDownloadBucketOperator
ImportError: cannot import name 'GCSDownloadBucketOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-02-24T22:16:02.280+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:16:02.292+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.226 seconds
[2023-02-24T22:16:32.478+0000] {processor.py:153} INFO - Started process (PID=1815) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:16:32.481+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:16:32.482+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:16:32.482+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:16:32.679+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:16:32.677+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 4, in <module>
    from airflow.providers.google.cloud.operators.gcs import GCSDownloadBucketOperator
ImportError: cannot import name 'GCSDownloadBucketOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-02-24T22:16:32.680+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:16:32.691+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.219 seconds
[2023-02-24T22:17:03.673+0000] {processor.py:153} INFO - Started process (PID=1894) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:17:03.675+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:17:03.677+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:17:03.677+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:17:03.886+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:17:03.885+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 4, in <module>
    from airflow.providers.google.cloud.operators.gcs import GCSDownloadBucketOperator
ImportError: cannot import name 'GCSDownloadBucketOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-02-24T22:17:03.887+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:17:03.899+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.231 seconds
[2023-02-24T22:17:34.639+0000] {processor.py:153} INFO - Started process (PID=1973) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:17:34.641+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:17:34.642+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:17:34.642+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:17:34.835+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:17:34.834+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 4, in <module>
    from airflow.providers.google.cloud.operators.gcs import GCSDownloadBucketOperator
ImportError: cannot import name 'GCSDownloadBucketOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-02-24T22:17:34.836+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:17:34.848+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.211 seconds
[2023-02-24T22:18:05.764+0000] {processor.py:153} INFO - Started process (PID=2039) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:18:05.766+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:18:05.766+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:18:05.766+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:18:05.955+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:18:05.954+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 4, in <module>
    from airflow.providers.google.cloud.operators.gcs import GCSDownloadBucketOperator
ImportError: cannot import name 'GCSDownloadBucketOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-02-24T22:18:05.956+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:18:05.968+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.207 seconds
[2023-02-24T22:18:36.984+0000] {processor.py:153} INFO - Started process (PID=2118) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:18:36.986+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:18:36.987+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:18:36.987+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:18:37.185+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:18:37.183+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 4, in <module>
    from airflow.providers.google.cloud.operators.gcs import GCSDownloadBucketOperator
ImportError: cannot import name 'GCSDownloadBucketOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-02-24T22:18:37.185+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:18:37.197+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.218 seconds
[2023-02-24T22:18:59.315+0000] {processor.py:153} INFO - Started process (PID=2167) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:18:59.316+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:18:59.317+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:18:59.317+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:18:59.509+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:18:59.508+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 3, in <module>
    from airflow.providers.google.cloud.operators.gcs import GCSDownloadBucketOperator
ImportError: cannot import name 'GCSDownloadBucketOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-02-24T22:18:59.511+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:18:59.522+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.209 seconds
[2023-02-24T22:19:30.249+0000] {processor.py:153} INFO - Started process (PID=2244) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:19:30.251+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:19:30.252+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:19:30.252+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:19:30.454+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:19:30.453+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 3, in <module>
    from airflow.providers.google.cloud.operators.gcs import GCSDownloadBucketOperator
ImportError: cannot import name 'GCSDownloadBucketOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-02-24T22:19:30.455+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:19:30.466+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.222 seconds
[2023-02-24T22:19:36.175+0000] {processor.py:153} INFO - Started process (PID=2264) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:19:36.177+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:19:36.178+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:19:36.178+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:19:36.205+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:19:36.203+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 27, in <module>
    google_cloud_conn_id=connection_id,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 123, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 743, in __init__
    f"Invalid arguments were passed to {self.__class__.__name__} (task_id: {task_id}). "
airflow.exceptions.AirflowException: Invalid arguments were passed to BaseSensorOperator (task_id: gcs_sensor). Invalid arguments were:
**kwargs: {'bucket': 'airflow-gcs-bq', 'object': 'airflow-gcs-bq/update.csv', 'google_cloud_conn_id': 'airflow-gcs-bq'}
[2023-02-24T22:19:36.206+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:19:36.222+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.053 seconds
[2023-02-24T22:20:06.538+0000] {processor.py:153} INFO - Started process (PID=2344) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:20:06.540+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:20:06.541+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:20:06.541+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:20:06.551+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:20:06.550+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 27, in <module>
    google_cloud_conn_id=connection_id,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 123, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 743, in __init__
    f"Invalid arguments were passed to {self.__class__.__name__} (task_id: {task_id}). "
airflow.exceptions.AirflowException: Invalid arguments were passed to BaseSensorOperator (task_id: gcs_sensor). Invalid arguments were:
**kwargs: {'bucket': 'airflow-gcs-bq', 'object': 'airflow-gcs-bq/update.csv', 'google_cloud_conn_id': 'airflow-gcs-bq'}
[2023-02-24T22:20:06.552+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:20:06.567+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.031 seconds
[2023-02-24T22:20:36.666+0000] {processor.py:153} INFO - Started process (PID=2423) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:20:36.669+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:20:36.670+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:20:36.670+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:20:36.688+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:20:36.686+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 27, in <module>
    google_cloud_conn_id=connection_id,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 123, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 743, in __init__
    f"Invalid arguments were passed to {self.__class__.__name__} (task_id: {task_id}). "
airflow.exceptions.AirflowException: Invalid arguments were passed to BaseSensorOperator (task_id: gcs_sensor). Invalid arguments were:
**kwargs: {'bucket': 'airflow-gcs-bq', 'object': 'airflow-gcs-bq/update.csv', 'google_cloud_conn_id': 'airflow-gcs-bq'}
[2023-02-24T22:20:36.689+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:20:36.707+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.046 seconds
[2023-02-24T22:21:06.751+0000] {processor.py:153} INFO - Started process (PID=2489) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:21:06.757+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:21:06.760+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:21:06.759+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:21:06.773+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:21:06.771+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 27, in <module>
    google_cloud_conn_id=connection_id,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 123, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 743, in __init__
    f"Invalid arguments were passed to {self.__class__.__name__} (task_id: {task_id}). "
airflow.exceptions.AirflowException: Invalid arguments were passed to BaseSensorOperator (task_id: gcs_sensor). Invalid arguments were:
**kwargs: {'bucket': 'airflow-gcs-bq', 'object': 'airflow-gcs-bq/update.csv', 'google_cloud_conn_id': 'airflow-gcs-bq'}
[2023-02-24T22:21:06.774+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:21:06.791+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.044 seconds
[2023-02-24T22:21:37.689+0000] {processor.py:153} INFO - Started process (PID=2568) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:21:37.692+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:21:37.694+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:21:37.694+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:21:37.712+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:21:37.709+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 27, in <module>
    google_cloud_conn_id=connection_id,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 123, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 743, in __init__
    f"Invalid arguments were passed to {self.__class__.__name__} (task_id: {task_id}). "
airflow.exceptions.AirflowException: Invalid arguments were passed to BaseSensorOperator (task_id: gcs_sensor). Invalid arguments were:
**kwargs: {'bucket': 'airflow-gcs-bq', 'object': 'airflow-gcs-bq/update.csv', 'google_cloud_conn_id': 'airflow-gcs-bq'}
[2023-02-24T22:21:37.714+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:21:37.737+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.051 seconds
[2023-02-24T22:22:08.517+0000] {processor.py:153} INFO - Started process (PID=2647) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:22:08.520+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:22:08.522+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:22:08.521+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:22:08.539+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:22:08.537+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 27, in <module>
    google_cloud_conn_id=connection_id,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 123, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 743, in __init__
    f"Invalid arguments were passed to {self.__class__.__name__} (task_id: {task_id}). "
airflow.exceptions.AirflowException: Invalid arguments were passed to BaseSensorOperator (task_id: gcs_sensor). Invalid arguments were:
**kwargs: {'bucket': 'airflow-gcs-bq', 'object': 'airflow-gcs-bq/update.csv', 'google_cloud_conn_id': 'airflow-gcs-bq'}
[2023-02-24T22:22:08.540+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:22:08.559+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.046 seconds
[2023-02-24T22:22:39.542+0000] {processor.py:153} INFO - Started process (PID=2726) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:22:39.545+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:22:39.546+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:22:39.546+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:22:39.563+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:22:39.561+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 27, in <module>
    google_cloud_conn_id=connection_id,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 123, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 743, in __init__
    f"Invalid arguments were passed to {self.__class__.__name__} (task_id: {task_id}). "
airflow.exceptions.AirflowException: Invalid arguments were passed to BaseSensorOperator (task_id: gcs_sensor). Invalid arguments were:
**kwargs: {'bucket': 'airflow-gcs-bq', 'object': 'airflow-gcs-bq/update.csv', 'google_cloud_conn_id': 'airflow-gcs-bq'}
[2023-02-24T22:22:39.565+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:22:39.587+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.050 seconds
[2023-02-24T22:23:10.470+0000] {processor.py:153} INFO - Started process (PID=2805) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:23:10.471+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:23:10.472+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:23:10.472+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:23:10.485+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:23:10.483+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 27, in <module>
    google_cloud_conn_id=connection_id,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 123, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 743, in __init__
    f"Invalid arguments were passed to {self.__class__.__name__} (task_id: {task_id}). "
airflow.exceptions.AirflowException: Invalid arguments were passed to BaseSensorOperator (task_id: gcs_sensor). Invalid arguments were:
**kwargs: {'bucket': 'airflow-gcs-bq', 'object': 'airflow-gcs-bq/update.csv', 'google_cloud_conn_id': 'airflow-gcs-bq'}
[2023-02-24T22:23:10.486+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:23:10.503+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.036 seconds
[2023-02-24T22:23:41.484+0000] {processor.py:153} INFO - Started process (PID=2871) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:23:41.486+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:23:41.487+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:23:41.487+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:23:41.503+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:23:41.501+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 27, in <module>
    google_cloud_conn_id=connection_id,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 123, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 743, in __init__
    f"Invalid arguments were passed to {self.__class__.__name__} (task_id: {task_id}). "
airflow.exceptions.AirflowException: Invalid arguments were passed to BaseSensorOperator (task_id: gcs_sensor). Invalid arguments were:
**kwargs: {'bucket': 'airflow-gcs-bq', 'object': 'airflow-gcs-bq/update.csv', 'google_cloud_conn_id': 'airflow-gcs-bq'}
[2023-02-24T22:23:41.505+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:23:41.523+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.044 seconds
[2023-02-24T22:24:11.673+0000] {processor.py:153} INFO - Started process (PID=2950) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:24:11.675+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:24:11.676+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:24:11.676+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:24:11.690+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:24:11.688+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 27, in <module>
    google_cloud_conn_id=connection_id,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 123, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 743, in __init__
    f"Invalid arguments were passed to {self.__class__.__name__} (task_id: {task_id}). "
airflow.exceptions.AirflowException: Invalid arguments were passed to BaseSensorOperator (task_id: gcs_sensor). Invalid arguments were:
**kwargs: {'bucket': 'airflow-gcs-bq', 'object': 'airflow-gcs-bq/update.csv', 'google_cloud_conn_id': 'airflow-gcs-bq'}
[2023-02-24T22:24:11.691+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:24:11.712+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.043 seconds
[2023-02-24T22:24:28.834+0000] {processor.py:153} INFO - Started process (PID=2974) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:24:28.835+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:24:28.836+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:24:28.836+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:24:29.152+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:24:29.150+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.providers.google.cloud.sensors.gcs import GoogleCloudStorageObjectSensor
ImportError: cannot import name 'GoogleCloudStorageObjectSensor' from 'airflow.providers.google.cloud.sensors.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/sensors/gcs.py)
[2023-02-24T22:24:29.152+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:24:29.164+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.333 seconds
[2023-02-24T22:24:59.835+0000] {processor.py:153} INFO - Started process (PID=3044) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:24:59.837+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:24:59.838+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:24:59.838+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:25:00.036+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:25:00.035+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.providers.google.cloud.sensors.gcs import GoogleCloudStorageObjectSensor
ImportError: cannot import name 'GoogleCloudStorageObjectSensor' from 'airflow.providers.google.cloud.sensors.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/sensors/gcs.py)
[2023-02-24T22:25:00.037+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:25:00.048+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.219 seconds
[2023-02-24T22:25:30.987+0000] {processor.py:153} INFO - Started process (PID=3122) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:25:30.988+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:25:30.989+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:25:30.989+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:25:31.191+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:25:31.189+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.providers.google.cloud.sensors.gcs import GoogleCloudStorageObjectSensor
ImportError: cannot import name 'GoogleCloudStorageObjectSensor' from 'airflow.providers.google.cloud.sensors.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/sensors/gcs.py)
[2023-02-24T22:25:31.192+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:25:31.204+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.221 seconds
[2023-02-24T22:26:01.303+0000] {processor.py:153} INFO - Started process (PID=3201) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:26:01.305+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:26:01.306+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:26:01.306+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:26:01.505+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:26:01.503+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.providers.google.cloud.sensors.gcs import GoogleCloudStorageObjectSensor
ImportError: cannot import name 'GoogleCloudStorageObjectSensor' from 'airflow.providers.google.cloud.sensors.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/sensors/gcs.py)
[2023-02-24T22:26:01.505+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:26:01.518+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.220 seconds
[2023-02-24T22:26:31.618+0000] {processor.py:153} INFO - Started process (PID=3267) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:26:31.619+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:26:31.620+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:26:31.620+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:26:31.801+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:26:31.800+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.providers.google.cloud.sensors.gcs import GoogleCloudStorageObjectSensor
ImportError: cannot import name 'GoogleCloudStorageObjectSensor' from 'airflow.providers.google.cloud.sensors.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/sensors/gcs.py)
[2023-02-24T22:26:31.802+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:26:31.814+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.198 seconds
[2023-02-24T22:27:02.745+0000] {processor.py:153} INFO - Started process (PID=3346) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:27:02.747+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:27:02.748+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:27:02.748+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:27:02.939+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:27:02.938+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.providers.google.cloud.sensors.gcs import GoogleCloudStorageObjectSensor
ImportError: cannot import name 'GoogleCloudStorageObjectSensor' from 'airflow.providers.google.cloud.sensors.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/sensors/gcs.py)
[2023-02-24T22:27:02.940+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:27:02.952+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.212 seconds
[2023-02-24T22:27:33.931+0000] {processor.py:153} INFO - Started process (PID=3426) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:27:33.934+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:27:33.935+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:27:33.935+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:27:34.125+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:27:34.123+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.providers.google.cloud.sensors.gcs import GoogleCloudStorageObjectSensor
ImportError: cannot import name 'GoogleCloudStorageObjectSensor' from 'airflow.providers.google.cloud.sensors.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/sensors/gcs.py)
[2023-02-24T22:27:34.126+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:27:34.137+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.210 seconds
[2023-02-24T22:28:05.164+0000] {processor.py:153} INFO - Started process (PID=3505) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:28:05.165+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:28:05.166+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:28:05.166+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:28:05.363+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:28:05.362+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.providers.google.cloud.sensors.gcs import GoogleCloudStorageObjectSensor
ImportError: cannot import name 'GoogleCloudStorageObjectSensor' from 'airflow.providers.google.cloud.sensors.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/sensors/gcs.py)
[2023-02-24T22:28:05.364+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:28:05.375+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.214 seconds
[2023-02-24T22:30:12.537+0000] {processor.py:153} INFO - Started process (PID=33) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:30:12.540+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:30:12.541+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:30:12.541+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:30:12.696+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:30:12.693+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.providers.google.cloud.sensors.gcs import GoogleCloudStorageObjectSensor
ImportError: cannot import name 'GoogleCloudStorageObjectSensor' from 'airflow.providers.google.cloud.sensors.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/sensors/gcs.py)
[2023-02-24T22:30:12.696+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:30:12.712+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.180 seconds
[2023-02-24T22:30:43.199+0000] {processor.py:153} INFO - Started process (PID=112) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:30:43.201+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:30:43.202+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:30:43.202+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:30:43.325+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:30:43.323+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.providers.google.cloud.sensors.gcs import GoogleCloudStorageObjectSensor
ImportError: cannot import name 'GoogleCloudStorageObjectSensor' from 'airflow.providers.google.cloud.sensors.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/sensors/gcs.py)
[2023-02-24T22:30:43.325+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:30:43.338+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.143 seconds
[2023-02-24T22:31:14.189+0000] {processor.py:153} INFO - Started process (PID=178) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:31:14.190+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:31:14.191+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:31:14.191+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:31:14.295+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:31:14.294+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.providers.google.cloud.sensors.gcs import GoogleCloudStorageObjectSensor
ImportError: cannot import name 'GoogleCloudStorageObjectSensor' from 'airflow.providers.google.cloud.sensors.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/sensors/gcs.py)
[2023-02-24T22:31:14.296+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:31:14.309+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.123 seconds
[2023-02-24T22:42:14.910+0000] {processor.py:153} INFO - Started process (PID=33) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:42:14.912+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:42:14.913+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:42:14.913+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:42:15.080+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:42:15.078+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.providers.google.cloud.sensors.gcs import GoogleCloudStorageObjectSensor
ImportError: cannot import name 'GoogleCloudStorageObjectSensor' from 'airflow.providers.google.cloud.sensors.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/sensors/gcs.py)
[2023-02-24T22:42:15.080+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:42:15.100+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.194 seconds
[2023-02-24T22:42:45.522+0000] {processor.py:153} INFO - Started process (PID=112) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:42:45.523+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:42:45.525+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:42:45.524+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:42:45.681+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:42:45.680+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.providers.google.cloud.sensors.gcs import GoogleCloudStorageObjectSensor
ImportError: cannot import name 'GoogleCloudStorageObjectSensor' from 'airflow.providers.google.cloud.sensors.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/sensors/gcs.py)
[2023-02-24T22:42:45.682+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:42:45.693+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.179 seconds
[2023-02-24T22:43:16.453+0000] {processor.py:153} INFO - Started process (PID=178) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:43:16.455+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:43:16.456+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:43:16.455+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:43:16.561+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:43:16.559+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.providers.google.cloud.sensors.gcs import GoogleCloudStorageObjectSensor
ImportError: cannot import name 'GoogleCloudStorageObjectSensor' from 'airflow.providers.google.cloud.sensors.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/sensors/gcs.py)
[2023-02-24T22:43:16.562+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:43:16.575+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.125 seconds
[2023-02-24T22:43:47.410+0000] {processor.py:153} INFO - Started process (PID=258) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:43:47.413+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:43:47.414+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:43:47.414+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:43:47.520+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:43:47.519+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.providers.google.cloud.sensors.gcs import GoogleCloudStorageObjectSensor
ImportError: cannot import name 'GoogleCloudStorageObjectSensor' from 'airflow.providers.google.cloud.sensors.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/sensors/gcs.py)
[2023-02-24T22:43:47.520+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:43:47.532+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.128 seconds
[2023-02-24T22:44:18.284+0000] {processor.py:153} INFO - Started process (PID=337) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:44:18.286+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:44:18.287+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:44:18.287+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:44:18.391+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:44:18.389+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.providers.google.cloud.sensors.gcs import GoogleCloudStorageObjectSensor
ImportError: cannot import name 'GoogleCloudStorageObjectSensor' from 'airflow.providers.google.cloud.sensors.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/sensors/gcs.py)
[2023-02-24T22:44:18.391+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:44:18.405+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.127 seconds
[2023-02-24T22:44:44.150+0000] {processor.py:153} INFO - Started process (PID=403) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:44:44.153+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:44:44.154+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:44:44.154+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:44:44.259+0000] {processor.py:753} INFO - DAG(s) dict_keys(['update-filter']) retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:44:44.356+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:44:44.356+0000] {manager.py:504} INFO - Created Permission View: can edit on DAG:update-filter
[2023-02-24T22:44:44.361+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:44:44.361+0000] {manager.py:504} INFO - Created Permission View: can delete on DAG:update-filter
[2023-02-24T22:44:44.364+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:44:44.364+0000] {manager.py:504} INFO - Created Permission View: can read on DAG:update-filter
[2023-02-24T22:44:44.365+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:44:44.365+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T22:44:44.372+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:44:44.372+0000] {dag.py:2711} INFO - Creating ORM DAG for update-filter
[2023-02-24T22:44:44.521+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:44:44.521+0000] {dag.py:3441} INFO - Setting next_dagrun for update-filter to None, run_after=None
[2023-02-24T22:44:44.532+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.385 seconds
[2023-02-24T22:45:15.531+0000] {processor.py:153} INFO - Started process (PID=482) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:45:15.533+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:45:15.534+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:45:15.534+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:45:15.677+0000] {processor.py:753} INFO - DAG(s) dict_keys(['update-filter']) retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:45:15.699+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:45:15.698+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T22:45:15.714+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:45:15.714+0000] {dag.py:3441} INFO - Setting next_dagrun for update-filter to None, run_after=None
[2023-02-24T22:45:15.724+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.198 seconds
[2023-02-24T22:45:45.854+0000] {processor.py:153} INFO - Started process (PID=561) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:45:45.859+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:45:45.860+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:45:45.860+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:45:45.993+0000] {processor.py:753} INFO - DAG(s) dict_keys(['update-filter']) retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:45:46.014+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:45:46.014+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T22:45:46.033+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:45:46.033+0000] {dag.py:3441} INFO - Setting next_dagrun for update-filter to None, run_after=None
[2023-02-24T22:45:46.045+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.195 seconds
[2023-02-24T22:46:16.106+0000] {processor.py:153} INFO - Started process (PID=626) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:46:16.109+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:46:16.110+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:46:16.110+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:46:16.213+0000] {processor.py:753} INFO - DAG(s) dict_keys(['update-filter']) retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:46:16.229+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:46:16.229+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T22:46:16.241+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:46:16.241+0000] {dag.py:3441} INFO - Setting next_dagrun for update-filter to None, run_after=None
[2023-02-24T22:46:16.250+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.149 seconds
[2023-02-24T22:46:47.208+0000] {processor.py:153} INFO - Started process (PID=704) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:46:47.210+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:46:47.211+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:46:47.211+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:46:47.313+0000] {processor.py:753} INFO - DAG(s) dict_keys(['update-filter']) retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:46:47.329+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:46:47.329+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T22:46:47.343+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:46:47.343+0000] {dag.py:3441} INFO - Setting next_dagrun for update-filter to None, run_after=None
[2023-02-24T22:46:47.352+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.148 seconds
[2023-02-24T22:47:17.447+0000] {processor.py:153} INFO - Started process (PID=783) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:47:17.449+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:47:17.450+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:47:17.450+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:47:17.553+0000] {processor.py:753} INFO - DAG(s) dict_keys(['update-filter']) retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:47:17.569+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:47:17.569+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T22:47:17.582+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:47:17.582+0000] {dag.py:3441} INFO - Setting next_dagrun for update-filter to None, run_after=None
[2023-02-24T22:47:17.591+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.148 seconds
[2023-02-24T22:47:48.382+0000] {processor.py:153} INFO - Started process (PID=862) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:47:48.384+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:47:48.385+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:47:48.385+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:47:48.532+0000] {processor.py:753} INFO - DAG(s) dict_keys(['update-filter']) retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:47:48.559+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:47:48.559+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T22:47:48.580+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:47:48.580+0000] {dag.py:3441} INFO - Setting next_dagrun for update-filter to None, run_after=None
[2023-02-24T22:47:48.593+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.213 seconds
[2023-02-24T22:48:19.584+0000] {processor.py:153} INFO - Started process (PID=928) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:48:19.585+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:48:19.586+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:48:19.586+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:48:19.687+0000] {processor.py:753} INFO - DAG(s) dict_keys(['update-filter']) retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:48:19.704+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:48:19.703+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T22:48:19.717+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:48:19.717+0000] {dag.py:3441} INFO - Setting next_dagrun for update-filter to None, run_after=None
[2023-02-24T22:48:19.728+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.146 seconds
[2023-02-24T22:48:50.618+0000] {processor.py:153} INFO - Started process (PID=1007) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:48:50.619+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:48:50.620+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:48:50.620+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:48:50.742+0000] {processor.py:753} INFO - DAG(s) dict_keys(['update-filter']) retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:48:50.758+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:48:50.758+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T22:48:50.772+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:48:50.772+0000] {dag.py:3441} INFO - Setting next_dagrun for update-filter to None, run_after=None
[2023-02-24T22:48:50.783+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.169 seconds
[2023-02-24T22:49:21.447+0000] {processor.py:153} INFO - Started process (PID=1086) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:49:21.448+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:49:21.449+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:49:21.449+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:49:21.540+0000] {processor.py:753} INFO - DAG(s) dict_keys(['update-filter']) retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:49:21.555+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:49:21.555+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T22:49:21.567+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:49:21.567+0000] {dag.py:3441} INFO - Setting next_dagrun for update-filter to None, run_after=None
[2023-02-24T22:49:21.576+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.131 seconds
[2023-02-24T22:49:52.492+0000] {processor.py:153} INFO - Started process (PID=1165) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:49:52.495+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:49:52.497+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:49:52.496+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:49:52.603+0000] {processor.py:753} INFO - DAG(s) dict_keys(['update-filter']) retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:49:52.617+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:49:52.617+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T22:49:52.629+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:49:52.629+0000] {dag.py:3441} INFO - Setting next_dagrun for update-filter to None, run_after=None
[2023-02-24T22:49:52.638+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.151 seconds
[2023-02-24T22:50:23.352+0000] {processor.py:153} INFO - Started process (PID=1232) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:50:23.354+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:50:23.355+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:50:23.355+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:50:23.462+0000] {processor.py:753} INFO - DAG(s) dict_keys(['update-filter']) retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:50:23.478+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:50:23.478+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T22:50:23.491+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:50:23.491+0000] {dag.py:3441} INFO - Setting next_dagrun for update-filter to None, run_after=None
[2023-02-24T22:50:23.502+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.155 seconds
[2023-02-24T22:50:54.466+0000] {processor.py:153} INFO - Started process (PID=1311) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:50:54.468+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:50:54.469+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:50:54.469+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:50:54.589+0000] {processor.py:753} INFO - DAG(s) dict_keys(['update-filter']) retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:50:54.605+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:50:54.605+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T22:50:54.620+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:50:54.620+0000] {dag.py:3441} INFO - Setting next_dagrun for update-filter to None, run_after=None
[2023-02-24T22:50:54.631+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.169 seconds
[2023-02-24T22:51:24.680+0000] {processor.py:153} INFO - Started process (PID=1391) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:51:24.681+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:51:24.682+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:51:24.682+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:51:24.780+0000] {processor.py:753} INFO - DAG(s) dict_keys(['update-filter']) retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:51:24.795+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:51:24.795+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T22:51:24.809+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:51:24.809+0000] {dag.py:3441} INFO - Setting next_dagrun for update-filter to None, run_after=None
[2023-02-24T22:51:24.821+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.143 seconds
[2023-02-24T22:51:54.860+0000] {processor.py:153} INFO - Started process (PID=1464) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:51:54.861+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:51:54.862+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:51:54.862+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:51:54.958+0000] {processor.py:753} INFO - DAG(s) dict_keys(['update-filter']) retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:51:54.974+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:51:54.974+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T22:51:54.987+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:51:54.987+0000] {dag.py:3441} INFO - Setting next_dagrun for update-filter to None, run_after=None
[2023-02-24T22:51:54.997+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.140 seconds
[2023-02-24T22:52:25.082+0000] {processor.py:153} INFO - Started process (PID=1534) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:52:25.084+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:52:25.085+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:52:25.085+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:52:25.194+0000] {processor.py:753} INFO - DAG(s) dict_keys(['update-filter']) retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:52:25.210+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:52:25.210+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T22:52:25.224+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:52:25.223+0000] {dag.py:3441} INFO - Setting next_dagrun for update-filter to None, run_after=None
[2023-02-24T22:52:25.234+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.154 seconds
[2023-02-24T22:52:56.076+0000] {processor.py:153} INFO - Started process (PID=1612) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:52:56.077+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:52:56.078+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:52:56.078+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:52:56.206+0000] {processor.py:753} INFO - DAG(s) dict_keys(['update-filter']) retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:52:56.225+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:52:56.224+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T22:52:56.238+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:52:56.238+0000] {dag.py:3441} INFO - Setting next_dagrun for update-filter to None, run_after=None
[2023-02-24T22:52:56.252+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.180 seconds
[2023-02-24T22:53:27.027+0000] {processor.py:153} INFO - Started process (PID=1691) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:53:27.029+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:53:27.031+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:53:27.030+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:53:27.137+0000] {processor.py:753} INFO - DAG(s) dict_keys(['update-filter']) retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:53:27.152+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:53:27.152+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T22:53:27.165+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:53:27.165+0000] {dag.py:3441} INFO - Setting next_dagrun for update-filter to None, run_after=None
[2023-02-24T22:53:27.174+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.153 seconds
[2023-02-24T22:53:58.013+0000] {processor.py:153} INFO - Started process (PID=1757) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:53:58.016+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:53:58.018+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:53:58.018+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:53:58.127+0000] {processor.py:753} INFO - DAG(s) dict_keys(['update-filter']) retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:53:58.141+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:53:58.141+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T22:53:58.153+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:53:58.153+0000] {dag.py:3441} INFO - Setting next_dagrun for update-filter to None, run_after=None
[2023-02-24T22:53:58.162+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.155 seconds
[2023-02-24T22:54:28.271+0000] {processor.py:153} INFO - Started process (PID=1837) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:54:28.274+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:54:28.275+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:54:28.275+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:54:28.381+0000] {processor.py:753} INFO - DAG(s) dict_keys(['update-filter']) retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:54:28.397+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:54:28.396+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T22:54:28.409+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:54:28.409+0000] {dag.py:3441} INFO - Setting next_dagrun for update-filter to None, run_after=None
[2023-02-24T22:54:28.417+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.152 seconds
[2023-02-24T22:54:59.183+0000] {processor.py:153} INFO - Started process (PID=1916) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:54:59.185+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:54:59.187+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:54:59.187+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:54:59.296+0000] {processor.py:753} INFO - DAG(s) dict_keys(['update-filter']) retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:54:59.312+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:54:59.312+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T22:54:59.325+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:54:59.325+0000] {dag.py:3441} INFO - Setting next_dagrun for update-filter to None, run_after=None
[2023-02-24T22:54:59.335+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.155 seconds
[2023-02-24T22:55:30.239+0000] {processor.py:153} INFO - Started process (PID=1994) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:55:30.241+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:55:30.243+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:55:30.243+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:55:30.373+0000] {processor.py:753} INFO - DAG(s) dict_keys(['update-filter']) retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:55:30.387+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:55:30.387+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T22:55:30.399+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:55:30.399+0000] {dag.py:3441} INFO - Setting next_dagrun for update-filter to None, run_after=None
[2023-02-24T22:55:30.408+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.174 seconds
[2023-02-24T22:56:01.249+0000] {processor.py:153} INFO - Started process (PID=2060) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:56:01.251+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:56:01.252+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:56:01.252+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:56:01.352+0000] {processor.py:753} INFO - DAG(s) dict_keys(['update-filter']) retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:56:01.367+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:56:01.367+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T22:56:01.379+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:56:01.379+0000] {dag.py:3441} INFO - Setting next_dagrun for update-filter to None, run_after=None
[2023-02-24T22:56:01.388+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.142 seconds
[2023-02-24T22:56:32.125+0000] {processor.py:153} INFO - Started process (PID=2139) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:56:32.128+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:56:32.129+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:56:32.129+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:56:32.236+0000] {processor.py:753} INFO - DAG(s) dict_keys(['update-filter']) retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:56:32.250+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:56:32.250+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T22:56:32.263+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:56:32.263+0000] {dag.py:3441} INFO - Setting next_dagrun for update-filter to None, run_after=None
[2023-02-24T22:56:32.271+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.152 seconds
[2023-02-24T22:57:03.195+0000] {processor.py:153} INFO - Started process (PID=2218) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:57:03.197+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:57:03.198+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:57:03.198+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:57:03.308+0000] {processor.py:753} INFO - DAG(s) dict_keys(['update-filter']) retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:57:03.323+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:57:03.323+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T22:57:03.336+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:57:03.336+0000] {dag.py:3441} INFO - Setting next_dagrun for update-filter to None, run_after=None
[2023-02-24T22:57:03.345+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.155 seconds
[2023-02-24T22:57:34.291+0000] {processor.py:153} INFO - Started process (PID=2297) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:57:34.294+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:57:34.295+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:57:34.295+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:57:34.414+0000] {processor.py:753} INFO - DAG(s) dict_keys(['update-filter']) retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:57:34.429+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:57:34.429+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T22:57:34.441+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:57:34.441+0000] {dag.py:3441} INFO - Setting next_dagrun for update-filter to None, run_after=None
[2023-02-24T22:57:34.450+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.165 seconds
[2023-02-24T22:58:05.155+0000] {processor.py:153} INFO - Started process (PID=2363) to work on /opt/airflow/dags/update-filter.py
[2023-02-24T22:58:05.157+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-24T22:58:05.158+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:58:05.158+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-24T22:58:05.262+0000] {processor.py:753} INFO - DAG(s) dict_keys(['update-filter']) retrieved from /opt/airflow/dags/update-filter.py
[2023-02-24T22:58:05.277+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:58:05.277+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T22:58:05.291+0000] {logging_mixin.py:137} INFO - [2023-02-24T22:58:05.291+0000] {dag.py:3441} INFO - Setting next_dagrun for update-filter to None, run_after=None
[2023-02-24T22:58:05.301+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.150 seconds
