[2023-02-27T16:16:05.991+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: update-filter.load_to_bq manual__2023-02-27T16:16:02.551785+00:00 [queued]>
[2023-02-27T16:16:05.997+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: update-filter.load_to_bq manual__2023-02-27T16:16:02.551785+00:00 [queued]>
[2023-02-27T16:16:05.997+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-27T16:16:05.998+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-02-27T16:16:05.998+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-27T16:16:06.004+0000] {taskinstance.py:1300} INFO - Executing <Task(GCSToBigQueryOperator): load_to_bq> on 2023-02-27 16:16:02.551785+00:00
[2023-02-27T16:16:06.009+0000] {standard_task_runner.py:55} INFO - Started process 1065 to run task
[2023-02-27T16:16:06.012+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'update-filter', 'load_to_bq', 'manual__2023-02-27T16:16:02.551785+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/update-filter.py', '--cfg-path', '/tmp/tmpd2jca7ev']
[2023-02-27T16:16:06.013+0000] {standard_task_runner.py:83} INFO - Job 39: Subtask load_to_bq
[2023-02-27T16:16:06.054+0000] {task_command.py:388} INFO - Running <TaskInstance: update-filter.load_to_bq manual__2023-02-27T16:16:02.551785+00:00 [running]> on host d766c014b21e
[2023-02-27T16:16:06.091+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=update-filter
AIRFLOW_CTX_TASK_ID=load_to_bq
AIRFLOW_CTX_EXECUTION_DATE=2023-02-27T16:16:02.551785+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-27T16:16:02.551785+00:00
[2023-02-27T16:16:06.106+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/transfers/gcs_to_bigquery.py", line 322, in execute
    impersonation_chain=self.impersonation_chain,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 103, in __init__
    impersonation_chain=impersonation_chain,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 231, in __init__
    self.extras: dict = self.get_connection(self.gcp_conn_id).extra_dejson
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 435, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `google_cloud_default` isn't defined
[2023-02-27T16:16:06.108+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=update-filter, task_id=load_to_bq, execution_date=20230227T161602, start_date=20230227T161605, end_date=20230227T161606
[2023-02-27T16:16:06.114+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 39 for task load_to_bq (The conn_id `google_cloud_default` isn't defined; 1065)
[2023-02-27T16:16:06.144+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-02-27T16:16:06.161+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
