[2023-02-27T21:41:13.159+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: update-filter.filter_insert manual__2023-02-27T21:32:18.777155+00:00 [queued]>
[2023-02-27T21:41:13.166+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: update-filter.filter_insert manual__2023-02-27T21:32:18.777155+00:00 [queued]>
[2023-02-27T21:41:13.167+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-27T21:41:13.168+0000] {taskinstance.py:1280} INFO - Starting attempt 3 of 3
[2023-02-27T21:41:13.168+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-27T21:41:13.176+0000] {taskinstance.py:1300} INFO - Executing <Task(BigQueryInsertJobOperator): filter_insert> on 2023-02-27 21:32:18.777155+00:00
[2023-02-27T21:41:13.182+0000] {standard_task_runner.py:55} INFO - Started process 731 to run task
[2023-02-27T21:41:13.185+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'update-filter', 'filter_insert', 'manual__2023-02-27T21:32:18.777155+00:00', '--job-id', '78', '--raw', '--subdir', 'DAGS_FOLDER/update-filter.py', '--cfg-path', '/tmp/tmpk1o0xyow']
[2023-02-27T21:41:13.186+0000] {standard_task_runner.py:83} INFO - Job 78: Subtask filter_insert
[2023-02-27T21:41:13.241+0000] {task_command.py:388} INFO - Running <TaskInstance: update-filter.filter_insert manual__2023-02-27T21:32:18.777155+00:00 [running]> on host d766c014b21e
[2023-02-27T21:41:13.290+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=update-filter
AIRFLOW_CTX_TASK_ID=filter_insert
AIRFLOW_CTX_EXECUTION_DATE=2023-02-27T21:32:18.777155+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-27T21:32:18.777155+00:00
[2023-02-27T21:41:13.298+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-02-27T21:41:13.299+0000] {bigquery.py:2635} INFO - Executing: {'query': {'query': 'SELECT id, name FROM `***-gcs-bq.***_dataset.***-gcs-bq.***_dataset.upload`', 'destinationTable': {'projectId': '***-gcs-bq', 'datasetId': '***_dataset', 'tableId': '***-gcs-bq.***_dataset.filter'}, 'createDisposition': 'CREATE_NEVER', 'writeDisposition': 'WRITE_APPEND', 'schema': {'fields': [{'name': 'id', 'type': 'INTEGER', 'mode': 'REQUIRED'}, {'name': 'name', 'type': 'STRING', 'mode': 'REQUIRED'}]}}}'
[2023-02-27T21:41:13.341+0000] {bigquery.py:1542} INFO - Inserting job ***_update_filter_filter_insert_2023_02_27T21_32_18_777155_00_00_465a0f2c8d378c49bf6f0579220db587
[2023-02-27T21:41:14.254+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2636, in execute
    job = self._submit_job(hook, job_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2609, in _submit_job
    nowait=True,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 462, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1545, in insert_job
    job._begin()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1298, in _begin
    super(QueryJob, self)._begin(client=client, retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 518, in _begin
    timeout=timeout,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/client.py", line 782, in _call_api
    return call()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/retry.py", line 288, in retry_wrapped_func
    on_error=on_error,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/retry.py", line 190, in retry_target
    return target()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.BadRequest: 400 POST https://bigquery.googleapis.com/bigquery/v2/projects/airflow-gcs-bq/jobs?prettyPrint=false: Invalid table ID "airflow-gcs-bq.airflow_dataset.filter".

Location: None
Job ID: airflow_update_filter_filter_insert_2023_02_27T21_32_18_777155_00_00_465a0f2c8d378c49bf6f0579220db587

[2023-02-27T21:41:14.290+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=update-filter, task_id=filter_insert, execution_date=20230227T213218, start_date=20230227T214113, end_date=20230227T214114
[2023-02-27T21:41:14.307+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 78 for task filter_insert (400 POST https://bigquery.googleapis.com/bigquery/v2/projects/airflow-gcs-bq/jobs?prettyPrint=false: Invalid table ID "airflow-gcs-bq.airflow_dataset.filter".

Location: None
Job ID: airflow_update_filter_filter_insert_2023_02_27T21_32_18_777155_00_00_465a0f2c8d378c49bf6f0579220db587
; 731)
[2023-02-27T21:41:14.361+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-02-27T21:41:14.380+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
