[2023-02-23T22:05:15.282+0000] {processor.py:153} INFO - Started process (PID=10241) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T22:05:15.283+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T22:05:15.284+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:05:15.284+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T22:05:15.298+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:05:15.297+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.contrib.operators.gcs_to_local import GoogleCloudStorageToLocaFileOperator
ModuleNotFoundError: No module named 'airflow.contrib.operators.gcs_to_local'
[2023-02-23T22:05:15.298+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T22:05:15.313+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.034 seconds
[2023-02-23T22:05:46.084+0000] {processor.py:153} INFO - Started process (PID=10320) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T22:05:46.086+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T22:05:46.087+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:05:46.087+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T22:05:46.097+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:05:46.095+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.contrib.operators.gcs_to_local import GoogleCloudStorageToLocaFileOperator
ModuleNotFoundError: No module named 'airflow.contrib.operators.gcs_to_local'
[2023-02-23T22:05:46.098+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T22:05:46.118+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.039 seconds
[2023-02-23T22:06:16.945+0000] {processor.py:153} INFO - Started process (PID=10399) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T22:06:16.947+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T22:06:16.948+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:06:16.948+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T22:06:16.954+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:06:16.953+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.contrib.operators.gcs_to_local import GoogleCloudStorageToLocaFileOperator
ModuleNotFoundError: No module named 'airflow.contrib.operators.gcs_to_local'
[2023-02-23T22:06:16.955+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T22:06:16.972+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.032 seconds
[2023-02-23T22:06:47.786+0000] {processor.py:153} INFO - Started process (PID=10479) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T22:06:47.787+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T22:06:47.788+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:06:47.788+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T22:06:47.794+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:06:47.793+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.contrib.operators.gcs_to_local import GoogleCloudStorageToLocaFileOperator
ModuleNotFoundError: No module named 'airflow.contrib.operators.gcs_to_local'
[2023-02-23T22:06:47.795+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T22:06:47.812+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.030 seconds
[2023-02-23T22:07:18.637+0000] {processor.py:153} INFO - Started process (PID=10546) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T22:07:18.640+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T22:07:18.642+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:07:18.641+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T22:07:18.654+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:07:18.652+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.contrib.operators.gcs_to_local import GoogleCloudStorageToLocaFileOperator
ModuleNotFoundError: No module named 'airflow.contrib.operators.gcs_to_local'
[2023-02-23T22:07:18.655+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T22:07:18.676+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.045 seconds
[2023-02-23T22:07:49.719+0000] {processor.py:153} INFO - Started process (PID=10626) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T22:07:49.720+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T22:07:49.722+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:07:49.722+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T22:07:49.730+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:07:49.729+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.contrib.operators.gcs_to_local import GoogleCloudStorageToLocaFileOperator
ModuleNotFoundError: No module named 'airflow.contrib.operators.gcs_to_local'
[2023-02-23T22:07:49.732+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T22:07:49.752+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.039 seconds
[2023-02-23T22:08:20.516+0000] {processor.py:153} INFO - Started process (PID=10705) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T22:08:20.518+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T22:08:20.520+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:08:20.520+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T22:08:20.531+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:08:20.529+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.contrib.operators.gcs_to_local import GoogleCloudStorageToLocaFileOperator
ModuleNotFoundError: No module named 'airflow.contrib.operators.gcs_to_local'
[2023-02-23T22:08:20.532+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T22:08:20.551+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.040 seconds
[2023-02-23T22:08:34.105+0000] {processor.py:153} INFO - Started process (PID=10758) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T22:08:34.107+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T22:08:34.108+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:08:34.107+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T22:08:34.117+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:08:34.116+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.contrib.operators.gcs_check_operator import GoogleCloudStorageCheckOperator
ModuleNotFoundError: No module named 'airflow.contrib.operators.gcs_check_operator'
[2023-02-23T22:08:34.118+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T22:08:34.133+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.032 seconds
[2023-02-23T22:09:04.187+0000] {processor.py:153} INFO - Started process (PID=10837) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T22:09:04.190+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T22:09:04.191+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:09:04.191+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T22:09:04.199+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:09:04.197+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.contrib.operators.gcs_check_operator import GoogleCloudStorageCheckOperator
ModuleNotFoundError: No module named 'airflow.contrib.operators.gcs_check_operator'
[2023-02-23T22:09:04.200+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T22:09:04.217+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.034 seconds
[2023-02-23T22:09:34.384+0000] {processor.py:153} INFO - Started process (PID=10910) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T22:09:34.386+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T22:09:34.387+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:09:34.387+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T22:09:34.393+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:09:34.392+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.contrib.operators.gcs_check_operator import GoogleCloudStorageCheckOperator
ModuleNotFoundError: No module named 'airflow.contrib.operators.gcs_check_operator'
[2023-02-23T22:09:34.394+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T22:09:34.407+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.025 seconds
[2023-02-23T22:10:04.552+0000] {processor.py:153} INFO - Started process (PID=10982) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T22:10:04.554+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T22:10:04.555+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:10:04.555+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T22:10:04.561+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:10:04.560+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.contrib.operators.gcs_check_operator import GoogleCloudStorageCheckOperator
ModuleNotFoundError: No module named 'airflow.contrib.operators.gcs_check_operator'
[2023-02-23T22:10:04.561+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T22:10:04.576+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.027 seconds
[2023-02-23T22:10:34.678+0000] {processor.py:153} INFO - Started process (PID=11061) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T22:10:34.681+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T22:10:34.683+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:10:34.682+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T22:10:34.693+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:10:34.691+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.contrib.operators.gcs_check_operator import GoogleCloudStorageCheckOperator
ModuleNotFoundError: No module named 'airflow.contrib.operators.gcs_check_operator'
[2023-02-23T22:10:34.695+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T22:10:34.718+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.045 seconds
[2023-02-23T22:11:04.859+0000] {processor.py:153} INFO - Started process (PID=11140) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T22:11:04.861+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T22:11:04.862+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:11:04.862+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T22:11:04.867+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:11:04.866+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.contrib.operators.gcs_check_operator import GoogleCloudStorageCheckOperator
ModuleNotFoundError: No module named 'airflow.contrib.operators.gcs_check_operator'
[2023-02-23T22:11:04.868+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T22:11:04.882+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.025 seconds
[2023-02-23T22:11:35.636+0000] {processor.py:153} INFO - Started process (PID=11207) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T22:11:35.638+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T22:11:35.640+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:11:35.639+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T22:11:35.648+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:11:35.647+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.contrib.operators.gcs_check_operator import GoogleCloudStorageCheckOperator
ModuleNotFoundError: No module named 'airflow.contrib.operators.gcs_check_operator'
[2023-02-23T22:11:35.649+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T22:11:35.666+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.034 seconds
[2023-02-23T22:11:41.709+0000] {processor.py:153} INFO - Started process (PID=11221) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T22:11:41.711+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T22:11:41.713+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:11:41.713+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T22:11:41.730+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:11:41.728+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.contrib.operators.gcs_check_operator import GoogleCloudStorageCheckOperator
ModuleNotFoundError: No module named 'airflow.contrib.operators.gcs_check_operator'
[2023-02-23T22:11:41.731+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T22:11:41.749+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.046 seconds
[2023-02-23T22:12:12.524+0000] {processor.py:153} INFO - Started process (PID=11299) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T22:12:12.526+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T22:12:12.526+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:12:12.526+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T22:12:12.532+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:12:12.531+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.contrib.operators.gcs_check_operator import GoogleCloudStorageCheckOperator
ModuleNotFoundError: No module named 'airflow.contrib.operators.gcs_check_operator'
[2023-02-23T22:12:12.533+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T22:12:12.547+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.026 seconds
[2023-02-23T22:12:42.591+0000] {processor.py:153} INFO - Started process (PID=11366) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T22:12:42.593+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T22:12:42.595+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:12:42.594+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T22:12:42.605+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:12:42.603+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.contrib.operators.gcs_check_operator import GoogleCloudStorageCheckOperator
ModuleNotFoundError: No module named 'airflow.contrib.operators.gcs_check_operator'
[2023-02-23T22:12:42.607+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T22:12:42.635+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.048 seconds
[2023-02-23T22:13:12.928+0000] {processor.py:153} INFO - Started process (PID=11445) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T22:13:12.930+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T22:13:12.931+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:13:12.931+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T22:13:12.939+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:13:12.938+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.contrib.operators.gcs_check_operator import GoogleCloudStorageCheckOperator
ModuleNotFoundError: No module named 'airflow.contrib.operators.gcs_check_operator'
[2023-02-23T22:13:12.941+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T22:13:12.961+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.038 seconds
[2023-02-23T22:13:43.864+0000] {processor.py:153} INFO - Started process (PID=11524) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T22:13:43.866+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T22:13:43.867+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:13:43.866+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T22:13:43.873+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:13:43.872+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.contrib.operators.gcs_check_operator import GoogleCloudStorageCheckOperator
ModuleNotFoundError: No module named 'airflow.contrib.operators.gcs_check_operator'
[2023-02-23T22:13:43.874+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T22:13:43.891+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.030 seconds
[2023-02-23T22:14:14.864+0000] {processor.py:153} INFO - Started process (PID=11599) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T22:14:14.865+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T22:14:14.866+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:14:14.866+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T22:14:14.872+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:14:14.871+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.contrib.operators.gcs_check_operator import GoogleCloudStorageCheckOperator
ModuleNotFoundError: No module named 'airflow.contrib.operators.gcs_check_operator'
[2023-02-23T22:14:14.872+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T22:14:14.886+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.023 seconds
[2023-02-23T22:14:45.112+0000] {processor.py:153} INFO - Started process (PID=11669) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T22:14:45.115+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T22:14:45.116+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:14:45.116+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T22:14:45.128+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:14:45.126+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.contrib.operators.gcs_check_operator import GoogleCloudStorageCheckOperator
ModuleNotFoundError: No module named 'airflow.contrib.operators.gcs_check_operator'
[2023-02-23T22:14:45.129+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T22:14:45.151+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.043 seconds
[2023-02-23T22:15:15.417+0000] {processor.py:153} INFO - Started process (PID=11748) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T22:15:15.420+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T22:15:15.422+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:15:15.422+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T22:15:15.431+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:15:15.430+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.contrib.operators.gcs_check_operator import GoogleCloudStorageCheckOperator
ModuleNotFoundError: No module named 'airflow.contrib.operators.gcs_check_operator'
[2023-02-23T22:15:15.432+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T22:15:15.451+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.040 seconds
[2023-02-23T22:15:46.444+0000] {processor.py:153} INFO - Started process (PID=11827) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T22:15:46.445+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T22:15:46.445+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:15:46.445+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T22:15:46.451+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:15:46.450+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.contrib.operators.gcs_check_operator import GoogleCloudStorageCheckOperator
ModuleNotFoundError: No module named 'airflow.contrib.operators.gcs_check_operator'
[2023-02-23T22:15:46.451+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T22:15:46.465+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.023 seconds
[2023-02-23T22:16:17.301+0000] {processor.py:153} INFO - Started process (PID=11893) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T22:16:17.302+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T22:16:17.305+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:16:17.304+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T22:16:17.314+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:16:17.313+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.contrib.operators.gcs_check_operator import GoogleCloudStorageCheckOperator
ModuleNotFoundError: No module named 'airflow.contrib.operators.gcs_check_operator'
[2023-02-23T22:16:17.315+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T22:16:17.338+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.042 seconds
[2023-02-23T22:16:48.341+0000] {processor.py:153} INFO - Started process (PID=11971) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T22:16:48.342+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T22:16:48.344+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:16:48.344+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T22:16:48.353+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:16:48.351+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.contrib.operators.gcs_check_operator import GoogleCloudStorageCheckOperator
ModuleNotFoundError: No module named 'airflow.contrib.operators.gcs_check_operator'
[2023-02-23T22:16:48.354+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T22:16:48.375+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.041 seconds
[2023-02-23T22:17:18.522+0000] {processor.py:153} INFO - Started process (PID=12050) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T22:17:18.525+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T22:17:18.527+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:17:18.526+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T22:17:18.539+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:17:18.537+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.contrib.operators.gcs_check_operator import GoogleCloudStorageCheckOperator
ModuleNotFoundError: No module named 'airflow.contrib.operators.gcs_check_operator'
[2023-02-23T22:17:18.540+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T22:17:18.561+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.045 seconds
[2023-02-23T22:17:48.639+0000] {processor.py:153} INFO - Started process (PID=12129) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T22:17:48.641+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T22:17:48.641+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:17:48.641+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T22:17:48.646+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:17:48.645+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.contrib.operators.gcs_check_operator import GoogleCloudStorageCheckOperator
ModuleNotFoundError: No module named 'airflow.contrib.operators.gcs_check_operator'
[2023-02-23T22:17:48.647+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T22:17:48.661+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.023 seconds
[2023-02-23T22:18:19.695+0000] {processor.py:153} INFO - Started process (PID=12195) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T22:18:19.698+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T22:18:19.699+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:18:19.699+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T22:18:19.710+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:18:19.708+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.contrib.operators.gcs_check_operator import GoogleCloudStorageCheckOperator
ModuleNotFoundError: No module named 'airflow.contrib.operators.gcs_check_operator'
[2023-02-23T22:18:19.710+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T22:18:19.732+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.042 seconds
[2023-02-23T22:18:50.759+0000] {processor.py:153} INFO - Started process (PID=12274) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T22:18:50.761+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T22:18:50.762+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:18:50.762+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T22:18:50.772+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:18:50.771+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.contrib.operators.gcs_check_operator import GoogleCloudStorageCheckOperator
ModuleNotFoundError: No module named 'airflow.contrib.operators.gcs_check_operator'
[2023-02-23T22:18:50.773+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T22:18:50.796+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.042 seconds
[2023-02-23T22:19:21.086+0000] {processor.py:153} INFO - Started process (PID=12353) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T22:19:21.087+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T22:19:21.088+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:19:21.088+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T22:19:21.096+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:19:21.094+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.contrib.operators.gcs_check_operator import GoogleCloudStorageCheckOperator
ModuleNotFoundError: No module named 'airflow.contrib.operators.gcs_check_operator'
[2023-02-23T22:19:21.096+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T22:19:21.118+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.037 seconds
[2023-02-23T22:19:51.215+0000] {processor.py:153} INFO - Started process (PID=12428) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T22:19:51.216+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T22:19:51.217+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:19:51.217+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T22:19:51.223+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:19:51.222+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.contrib.operators.gcs_check_operator import GoogleCloudStorageCheckOperator
ModuleNotFoundError: No module named 'airflow.contrib.operators.gcs_check_operator'
[2023-02-23T22:19:51.224+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T22:19:51.240+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.027 seconds
[2023-02-23T22:20:21.388+0000] {processor.py:153} INFO - Started process (PID=12498) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T22:20:21.389+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T22:20:21.390+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:20:21.390+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T22:20:21.396+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:20:21.395+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.contrib.operators.gcs_check_operator import GoogleCloudStorageCheckOperator
ModuleNotFoundError: No module named 'airflow.contrib.operators.gcs_check_operator'
[2023-02-23T22:20:21.397+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T22:20:21.414+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.028 seconds
[2023-02-23T22:20:51.501+0000] {processor.py:153} INFO - Started process (PID=12578) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T22:20:51.503+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T22:20:51.505+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:20:51.505+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T22:20:51.516+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:20:51.514+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.contrib.operators.gcs_check_operator import GoogleCloudStorageCheckOperator
ModuleNotFoundError: No module named 'airflow.contrib.operators.gcs_check_operator'
[2023-02-23T22:20:51.517+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T22:20:51.543+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.047 seconds
[2023-02-23T22:21:21.727+0000] {processor.py:153} INFO - Started process (PID=12657) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T22:21:21.729+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T22:21:21.730+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:21:21.730+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T22:21:21.736+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:21:21.735+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.contrib.operators.gcs_check_operator import GoogleCloudStorageCheckOperator
ModuleNotFoundError: No module named 'airflow.contrib.operators.gcs_check_operator'
[2023-02-23T22:21:21.736+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T22:21:21.751+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.027 seconds
[2023-02-23T22:21:51.993+0000] {processor.py:153} INFO - Started process (PID=12723) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T22:21:51.994+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T22:21:51.995+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:21:51.995+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T22:21:52.002+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:21:52.001+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.contrib.operators.gcs_check_operator import GoogleCloudStorageCheckOperator
ModuleNotFoundError: No module named 'airflow.contrib.operators.gcs_check_operator'
[2023-02-23T22:21:52.003+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T22:21:52.019+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.029 seconds
[2023-02-23T22:22:02.153+0000] {processor.py:153} INFO - Started process (PID=12737) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T22:22:02.154+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T22:22:02.156+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:22:02.155+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T22:22:02.598+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:22:02.596+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 25, in <module>
    google_cloud_storage_conn_id=connection_id,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/sensors/gcs.py", line 80, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 123, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 743, in __init__
    f"Invalid arguments were passed to {self.__class__.__name__} (task_id: {task_id}). "
airflow.exceptions.AirflowException: Invalid arguments were passed to GCSObjectExistenceSensor (task_id: gcs_sensor). Invalid arguments were:
**kwargs: {'google_cloud_storage_conn_id': 'airflow-gcs-bq'}
[2023-02-23T22:22:02.598+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T22:22:02.610+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.461 seconds
[2023-02-23T22:22:08.999+0000] {processor.py:153} INFO - Started process (PID=12790) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T22:22:09.001+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T22:22:09.002+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:22:09.002+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T22:22:09.202+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:22:09.200+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 25, in <module>
    google_cloud_storage_conn_id=connection_id,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/sensors/gcs.py", line 80, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 123, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 743, in __init__
    f"Invalid arguments were passed to {self.__class__.__name__} (task_id: {task_id}). "
airflow.exceptions.AirflowException: Invalid arguments were passed to GCSObjectExistenceSensor (task_id: gcs_sensor). Invalid arguments were:
**kwargs: {'google_cloud_storage_conn_id': 'airflow-gcs-bq'}
[2023-02-23T22:22:09.203+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T22:22:09.217+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.223 seconds
[2023-02-23T22:22:39.367+0000] {processor.py:153} INFO - Started process (PID=12863) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T22:22:39.369+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T22:22:39.370+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:22:39.370+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T22:22:39.576+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:22:39.574+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 25, in <module>
    google_cloud_storage_conn_id=connection_id,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/sensors/gcs.py", line 80, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 123, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 743, in __init__
    f"Invalid arguments were passed to {self.__class__.__name__} (task_id: {task_id}). "
airflow.exceptions.AirflowException: Invalid arguments were passed to GCSObjectExistenceSensor (task_id: gcs_sensor). Invalid arguments were:
**kwargs: {'google_cloud_storage_conn_id': 'airflow-gcs-bq'}
[2023-02-23T22:22:39.577+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T22:22:39.590+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.225 seconds
[2023-02-23T22:23:10.576+0000] {processor.py:153} INFO - Started process (PID=12934) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T22:23:10.579+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T22:23:10.581+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:23:10.581+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T22:23:10.778+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:23:10.777+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 25, in <module>
    google_cloud_storage_conn_id=connection_id,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/sensors/gcs.py", line 80, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 123, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 743, in __init__
    f"Invalid arguments were passed to {self.__class__.__name__} (task_id: {task_id}). "
airflow.exceptions.AirflowException: Invalid arguments were passed to GCSObjectExistenceSensor (task_id: gcs_sensor). Invalid arguments were:
**kwargs: {'google_cloud_storage_conn_id': 'airflow-gcs-bq'}
[2023-02-23T22:23:10.779+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T22:23:10.790+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.220 seconds
[2023-02-23T22:23:41.841+0000] {processor.py:153} INFO - Started process (PID=13013) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T22:23:41.844+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T22:23:41.846+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:23:41.845+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T22:23:42.041+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:23:42.040+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 25, in <module>
    google_cloud_storage_conn_id=connection_id,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/sensors/gcs.py", line 80, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 123, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 743, in __init__
    f"Invalid arguments were passed to {self.__class__.__name__} (task_id: {task_id}). "
airflow.exceptions.AirflowException: Invalid arguments were passed to GCSObjectExistenceSensor (task_id: gcs_sensor). Invalid arguments were:
**kwargs: {'google_cloud_storage_conn_id': 'airflow-gcs-bq'}
[2023-02-23T22:23:42.042+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T22:23:42.053+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.217 seconds
[2023-02-23T22:24:13.052+0000] {processor.py:153} INFO - Started process (PID=13093) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T22:24:13.054+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T22:24:13.056+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:24:13.056+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T22:24:13.260+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:24:13.258+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 25, in <module>
    google_cloud_storage_conn_id=connection_id,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/sensors/gcs.py", line 80, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 123, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 743, in __init__
    f"Invalid arguments were passed to {self.__class__.__name__} (task_id: {task_id}). "
airflow.exceptions.AirflowException: Invalid arguments were passed to GCSObjectExistenceSensor (task_id: gcs_sensor). Invalid arguments were:
**kwargs: {'google_cloud_storage_conn_id': 'airflow-gcs-bq'}
[2023-02-23T22:24:13.260+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T22:24:13.278+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.230 seconds
[2023-02-23T22:24:44.186+0000] {processor.py:153} INFO - Started process (PID=13172) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T22:24:44.187+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T22:24:44.188+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:24:44.188+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T22:24:44.370+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:24:44.369+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 25, in <module>
    google_cloud_storage_conn_id=connection_id,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/sensors/gcs.py", line 80, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 123, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 743, in __init__
    f"Invalid arguments were passed to {self.__class__.__name__} (task_id: {task_id}). "
airflow.exceptions.AirflowException: Invalid arguments were passed to GCSObjectExistenceSensor (task_id: gcs_sensor). Invalid arguments were:
**kwargs: {'google_cloud_storage_conn_id': 'airflow-gcs-bq'}
[2023-02-23T22:24:44.371+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T22:24:44.382+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.199 seconds
[2023-02-23T22:25:14.437+0000] {processor.py:153} INFO - Started process (PID=13237) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T22:25:14.439+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T22:25:14.441+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:25:14.440+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T22:25:14.640+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:25:14.639+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 25, in <module>
    google_cloud_storage_conn_id=connection_id,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/sensors/gcs.py", line 80, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 123, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 743, in __init__
    f"Invalid arguments were passed to {self.__class__.__name__} (task_id: {task_id}). "
airflow.exceptions.AirflowException: Invalid arguments were passed to GCSObjectExistenceSensor (task_id: gcs_sensor). Invalid arguments were:
**kwargs: {'google_cloud_storage_conn_id': 'airflow-gcs-bq'}
[2023-02-23T22:25:14.641+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T22:25:14.654+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.221 seconds
[2023-02-23T22:25:45.584+0000] {processor.py:153} INFO - Started process (PID=13315) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T22:25:45.586+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T22:25:45.587+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:25:45.587+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T22:25:45.783+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:25:45.782+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 25, in <module>
    google_cloud_storage_conn_id=connection_id,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/sensors/gcs.py", line 80, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 123, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 743, in __init__
    f"Invalid arguments were passed to {self.__class__.__name__} (task_id: {task_id}). "
airflow.exceptions.AirflowException: Invalid arguments were passed to GCSObjectExistenceSensor (task_id: gcs_sensor). Invalid arguments were:
**kwargs: {'google_cloud_storage_conn_id': 'airflow-gcs-bq'}
[2023-02-23T22:25:45.784+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T22:25:45.795+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.216 seconds
[2023-02-23T22:26:16.671+0000] {processor.py:153} INFO - Started process (PID=13394) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T22:26:16.674+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T22:26:16.675+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:26:16.675+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T22:26:16.869+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:26:16.867+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 25, in <module>
    google_cloud_storage_conn_id=connection_id,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/sensors/gcs.py", line 80, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 123, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 743, in __init__
    f"Invalid arguments were passed to {self.__class__.__name__} (task_id: {task_id}). "
airflow.exceptions.AirflowException: Invalid arguments were passed to GCSObjectExistenceSensor (task_id: gcs_sensor). Invalid arguments were:
**kwargs: {'google_cloud_storage_conn_id': 'airflow-gcs-bq'}
[2023-02-23T22:26:16.870+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T22:26:16.881+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.215 seconds
[2023-02-23T22:26:47.728+0000] {processor.py:153} INFO - Started process (PID=13473) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T22:26:47.730+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T22:26:47.730+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:26:47.730+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T22:26:47.916+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:26:47.915+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 25, in <module>
    google_cloud_storage_conn_id=connection_id,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/sensors/gcs.py", line 80, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 123, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 743, in __init__
    f"Invalid arguments were passed to {self.__class__.__name__} (task_id: {task_id}). "
airflow.exceptions.AirflowException: Invalid arguments were passed to GCSObjectExistenceSensor (task_id: gcs_sensor). Invalid arguments were:
**kwargs: {'google_cloud_storage_conn_id': 'airflow-gcs-bq'}
[2023-02-23T22:26:47.917+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T22:26:47.927+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.202 seconds
[2023-02-23T22:27:18.070+0000] {processor.py:153} INFO - Started process (PID=13539) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T22:27:18.073+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T22:27:18.075+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:27:18.075+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T22:27:18.274+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:27:18.273+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 25, in <module>
    google_cloud_storage_conn_id=connection_id,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/sensors/gcs.py", line 80, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 123, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 743, in __init__
    f"Invalid arguments were passed to {self.__class__.__name__} (task_id: {task_id}). "
airflow.exceptions.AirflowException: Invalid arguments were passed to GCSObjectExistenceSensor (task_id: gcs_sensor). Invalid arguments were:
**kwargs: {'google_cloud_storage_conn_id': 'airflow-gcs-bq'}
[2023-02-23T22:27:18.275+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T22:27:18.286+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.222 seconds
[2023-02-23T22:27:22.345+0000] {processor.py:153} INFO - Started process (PID=13553) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T22:27:22.346+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T22:27:22.347+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:27:22.347+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T22:27:22.356+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:27:22.355+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.contrib.operators.gcs_check_operator import GoogleCloudStorageCheckOperator
ModuleNotFoundError: No module named 'airflow.contrib.operators.gcs_check_operator'
[2023-02-23T22:27:22.357+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T22:27:22.370+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.029 seconds
[2023-02-23T22:27:52.432+0000] {processor.py:153} INFO - Started process (PID=13619) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T22:27:52.436+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T22:27:52.437+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:27:52.437+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T22:27:52.451+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:27:52.449+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.contrib.operators.gcs_check_operator import GoogleCloudStorageCheckOperator
ModuleNotFoundError: No module named 'airflow.contrib.operators.gcs_check_operator'
[2023-02-23T22:27:52.452+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T22:27:52.474+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.048 seconds
[2023-02-23T22:32:15.837+0000] {processor.py:153} INFO - Started process (PID=34) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T22:32:15.838+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T22:32:15.839+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:32:15.839+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T22:32:15.848+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:32:15.846+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.contrib.operators.gcs_check_operator import GoogleCloudStorageCheckOperator
ModuleNotFoundError: No module named 'airflow.contrib.operators.gcs_check_operator'
[2023-02-23T22:32:15.849+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T22:32:15.878+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.045 seconds
[2023-02-23T22:32:46.369+0000] {processor.py:153} INFO - Started process (PID=113) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T22:32:46.370+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T22:32:46.371+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:32:46.371+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T22:32:46.377+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:32:46.376+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.contrib.operators.gcs_check_operator import GoogleCloudStorageCheckOperator
ModuleNotFoundError: No module named 'airflow.contrib.operators.gcs_check_operator'
[2023-02-23T22:32:46.377+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T22:32:46.393+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.028 seconds
[2023-02-23T22:38:45.554+0000] {processor.py:153} INFO - Started process (PID=34) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T22:38:45.555+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T22:38:45.556+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:38:45.556+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T22:38:45.568+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:38:45.566+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.contrib.operators.gcs_check_operator import GoogleCloudStorageCheckOperator
ModuleNotFoundError: No module named 'airflow.contrib.operators.gcs_check_operator'
[2023-02-23T22:38:45.569+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T22:38:45.591+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.041 seconds
[2023-02-23T22:39:16.002+0000] {processor.py:153} INFO - Started process (PID=114) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T22:39:16.003+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T22:39:16.004+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:39:16.004+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T22:39:16.013+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:39:16.011+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.contrib.operators.gcs_check_operator import GoogleCloudStorageCheckOperator
ModuleNotFoundError: No module named 'airflow.contrib.operators.gcs_check_operator'
[2023-02-23T22:39:16.014+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T22:39:16.030+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.033 seconds
[2023-02-23T22:39:46.068+0000] {processor.py:153} INFO - Started process (PID=180) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T22:39:46.069+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T22:39:46.070+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:39:46.070+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T22:39:46.078+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:39:46.076+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.contrib.operators.gcs_check_operator import GoogleCloudStorageCheckOperator
ModuleNotFoundError: No module named 'airflow.contrib.operators.gcs_check_operator'
[2023-02-23T22:39:46.079+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T22:39:46.096+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.032 seconds
[2023-02-23T22:40:16.236+0000] {processor.py:153} INFO - Started process (PID=259) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T22:40:16.239+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T22:40:16.240+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:40:16.240+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T22:40:16.250+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:40:16.248+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.contrib.operators.gcs_check_operator import GoogleCloudStorageCheckOperator
ModuleNotFoundError: No module named 'airflow.contrib.operators.gcs_check_operator'
[2023-02-23T22:40:16.251+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T22:40:16.272+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.042 seconds
[2023-02-23T22:40:46.360+0000] {processor.py:153} INFO - Started process (PID=338) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T22:40:46.362+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T22:40:46.363+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:40:46.363+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T22:40:46.372+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:40:46.370+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.contrib.operators.gcs_check_operator import GoogleCloudStorageCheckOperator
ModuleNotFoundError: No module named 'airflow.contrib.operators.gcs_check_operator'
[2023-02-23T22:40:46.373+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T22:40:46.390+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.034 seconds
[2023-02-23T22:41:16.484+0000] {processor.py:153} INFO - Started process (PID=404) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T22:41:16.485+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T22:41:16.486+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:41:16.486+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T22:41:16.491+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:41:16.490+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.contrib.operators.gcs_check_operator import GoogleCloudStorageCheckOperator
ModuleNotFoundError: No module named 'airflow.contrib.operators.gcs_check_operator'
[2023-02-23T22:41:16.492+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T22:41:16.505+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.024 seconds
[2023-02-23T22:41:47.499+0000] {processor.py:153} INFO - Started process (PID=483) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T22:41:47.502+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T22:41:47.503+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:41:47.503+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T22:41:47.511+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:41:47.510+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.contrib.operators.gcs_check_operator import GoogleCloudStorageCheckOperator
ModuleNotFoundError: No module named 'airflow.contrib.operators.gcs_check_operator'
[2023-02-23T22:41:47.512+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T22:41:47.530+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.036 seconds
[2023-02-23T22:42:18.237+0000] {processor.py:153} INFO - Started process (PID=562) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T22:42:18.239+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T22:42:18.240+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:42:18.240+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T22:42:18.249+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:42:18.248+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.contrib.operators.gcs_check_operator import GoogleCloudStorageCheckOperator
ModuleNotFoundError: No module named 'airflow.contrib.operators.gcs_check_operator'
[2023-02-23T22:42:18.250+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T22:42:18.269+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.040 seconds
[2023-02-23T22:42:49.055+0000] {processor.py:153} INFO - Started process (PID=641) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T22:42:49.056+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T22:42:49.057+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:42:49.057+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T22:42:49.065+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:42:49.063+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.contrib.operators.gcs_check_operator import GoogleCloudStorageCheckOperator
ModuleNotFoundError: No module named 'airflow.contrib.operators.gcs_check_operator'
[2023-02-23T22:42:49.065+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T22:42:49.082+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.031 seconds
[2023-02-23T22:43:19.849+0000] {processor.py:153} INFO - Started process (PID=707) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T22:43:19.853+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T22:43:19.854+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:43:19.854+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T22:43:19.864+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:43:19.862+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.contrib.operators.gcs_check_operator import GoogleCloudStorageCheckOperator
ModuleNotFoundError: No module named 'airflow.contrib.operators.gcs_check_operator'
[2023-02-23T22:43:19.865+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T22:43:19.884+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.040 seconds
[2023-02-23T22:43:50.639+0000] {processor.py:153} INFO - Started process (PID=786) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T22:43:50.640+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T22:43:50.641+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:43:50.641+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T22:43:50.646+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:43:50.645+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.contrib.operators.gcs_check_operator import GoogleCloudStorageCheckOperator
ModuleNotFoundError: No module named 'airflow.contrib.operators.gcs_check_operator'
[2023-02-23T22:43:50.647+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T22:43:50.661+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.025 seconds
[2023-02-23T22:44:21.562+0000] {processor.py:153} INFO - Started process (PID=866) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T22:44:21.564+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T22:44:21.566+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:44:21.565+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T22:44:21.574+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:44:21.573+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.contrib.operators.gcs_check_operator import GoogleCloudStorageCheckOperator
ModuleNotFoundError: No module named 'airflow.contrib.operators.gcs_check_operator'
[2023-02-23T22:44:21.575+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T22:44:21.594+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.037 seconds
[2023-02-23T22:44:52.481+0000] {processor.py:153} INFO - Started process (PID=945) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T22:44:52.483+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T22:44:52.484+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:44:52.484+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T22:44:52.491+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:44:52.490+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.contrib.operators.gcs_check_operator import GoogleCloudStorageCheckOperator
ModuleNotFoundError: No module named 'airflow.contrib.operators.gcs_check_operator'
[2023-02-23T22:44:52.492+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T22:44:52.508+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.031 seconds
[2023-02-23T22:45:23.276+0000] {processor.py:153} INFO - Started process (PID=1011) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T22:45:23.277+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T22:45:23.278+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:45:23.278+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T22:45:23.285+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:45:23.284+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.contrib.operators.gcs_check_operator import GoogleCloudStorageCheckOperator
ModuleNotFoundError: No module named 'airflow.contrib.operators.gcs_check_operator'
[2023-02-23T22:45:23.285+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T22:45:23.299+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.027 seconds
[2023-02-23T22:45:54.244+0000] {processor.py:153} INFO - Started process (PID=1090) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T22:45:54.246+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T22:45:54.247+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:45:54.247+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T22:45:54.255+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:45:54.253+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.contrib.operators.gcs_check_operator import GoogleCloudStorageCheckOperator
ModuleNotFoundError: No module named 'airflow.contrib.operators.gcs_check_operator'
[2023-02-23T22:45:54.256+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T22:45:54.276+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.037 seconds
[2023-02-23T22:46:25.069+0000] {processor.py:153} INFO - Started process (PID=1169) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T22:46:25.071+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T22:46:25.072+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:46:25.072+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T22:46:25.080+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:46:25.078+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.contrib.operators.gcs_check_operator import GoogleCloudStorageCheckOperator
ModuleNotFoundError: No module named 'airflow.contrib.operators.gcs_check_operator'
[2023-02-23T22:46:25.080+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T22:46:25.096+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.031 seconds
[2023-02-23T22:46:56.093+0000] {processor.py:153} INFO - Started process (PID=1248) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T22:46:56.095+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T22:46:56.096+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:46:56.096+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T22:46:56.103+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:46:56.101+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.contrib.operators.gcs_check_operator import GoogleCloudStorageCheckOperator
ModuleNotFoundError: No module named 'airflow.contrib.operators.gcs_check_operator'
[2023-02-23T22:46:56.103+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T22:46:56.121+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.032 seconds
[2023-02-23T22:47:26.923+0000] {processor.py:153} INFO - Started process (PID=1314) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T22:47:26.924+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T22:47:26.925+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:47:26.925+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T22:47:26.930+0000] {logging_mixin.py:137} INFO - [2023-02-23T22:47:26.929+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.contrib.operators.gcs_check_operator import GoogleCloudStorageCheckOperator
ModuleNotFoundError: No module named 'airflow.contrib.operators.gcs_check_operator'
[2023-02-23T22:47:26.931+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T22:47:26.945+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.026 seconds
[2023-02-23T23:07:08.322+0000] {processor.py:153} INFO - Started process (PID=34) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T23:07:08.325+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T23:07:08.326+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:07:08.326+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T23:07:08.334+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:07:08.332+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.contrib.operators.gcs_check_operator import GoogleCloudStorageCheckOperator
ModuleNotFoundError: No module named 'airflow.contrib.operators.gcs_check_operator'
[2023-02-23T23:07:08.335+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T23:07:08.358+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.041 seconds
[2023-02-23T23:07:38.902+0000] {processor.py:153} INFO - Started process (PID=114) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T23:07:38.904+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T23:07:38.905+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:07:38.905+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T23:07:38.913+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:07:38.911+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.contrib.operators.gcs_check_operator import GoogleCloudStorageCheckOperator
ModuleNotFoundError: No module named 'airflow.contrib.operators.gcs_check_operator'
[2023-02-23T23:07:38.914+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T23:07:38.947+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.048 seconds
[2023-02-23T23:08:09.223+0000] {processor.py:153} INFO - Started process (PID=180) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T23:08:09.225+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T23:08:09.226+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:08:09.226+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T23:08:09.233+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:08:09.232+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.contrib.operators.gcs_check_operator import GoogleCloudStorageCheckOperator
ModuleNotFoundError: No module named 'airflow.contrib.operators.gcs_check_operator'
[2023-02-23T23:08:09.234+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T23:08:09.253+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.034 seconds
[2023-02-23T23:08:40.271+0000] {processor.py:153} INFO - Started process (PID=259) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T23:08:40.273+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T23:08:40.275+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:08:40.275+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T23:08:40.282+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:08:40.281+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.contrib.operators.gcs_check_operator import GoogleCloudStorageCheckOperator
ModuleNotFoundError: No module named 'airflow.contrib.operators.gcs_check_operator'
[2023-02-23T23:08:40.283+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T23:08:40.301+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.035 seconds
[2023-02-23T23:09:11.194+0000] {processor.py:153} INFO - Started process (PID=338) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T23:09:11.196+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T23:09:11.197+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:09:11.197+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T23:09:11.208+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:09:11.206+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.contrib.operators.gcs_check_operator import GoogleCloudStorageCheckOperator
ModuleNotFoundError: No module named 'airflow.contrib.operators.gcs_check_operator'
[2023-02-23T23:09:11.209+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T23:09:11.228+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.040 seconds
[2023-02-23T23:09:41.908+0000] {processor.py:153} INFO - Started process (PID=417) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T23:09:41.909+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T23:09:41.910+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:09:41.910+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T23:09:41.916+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:09:41.915+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.contrib.operators.gcs_check_operator import GoogleCloudStorageCheckOperator
ModuleNotFoundError: No module named 'airflow.contrib.operators.gcs_check_operator'
[2023-02-23T23:09:41.917+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T23:09:41.933+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.028 seconds
[2023-02-23T23:10:12.716+0000] {processor.py:153} INFO - Started process (PID=483) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T23:10:12.716+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T23:10:12.717+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:10:12.717+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T23:10:12.722+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:10:12.721+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.contrib.operators.gcs_check_operator import GoogleCloudStorageCheckOperator
ModuleNotFoundError: No module named 'airflow.contrib.operators.gcs_check_operator'
[2023-02-23T23:10:12.723+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T23:10:12.740+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.026 seconds
[2023-02-23T23:10:43.465+0000] {processor.py:153} INFO - Started process (PID=561) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T23:10:43.467+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T23:10:43.468+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:10:43.468+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T23:10:43.476+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:10:43.474+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.contrib.operators.gcs_check_operator import GoogleCloudStorageCheckOperator
ModuleNotFoundError: No module named 'airflow.contrib.operators.gcs_check_operator'
[2023-02-23T23:10:43.476+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T23:10:43.493+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.032 seconds
[2023-02-23T23:11:23.098+0000] {processor.py:153} INFO - Started process (PID=34) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T23:11:23.099+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T23:11:23.100+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:11:23.100+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T23:11:23.108+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:11:23.105+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.contrib.operators.gcs_check_operator import GoogleCloudStorageCheckOperator
ModuleNotFoundError: No module named 'airflow.contrib.operators.gcs_check_operator'
[2023-02-23T23:11:23.109+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T23:11:23.134+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.040 seconds
[2023-02-23T23:11:53.336+0000] {processor.py:153} INFO - Started process (PID=112) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T23:11:53.338+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T23:11:53.340+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:11:53.340+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T23:11:53.346+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:11:53.345+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.contrib.operators.gcs_check_operator import GoogleCloudStorageCheckOperator
ModuleNotFoundError: No module named 'airflow.contrib.operators.gcs_check_operator'
[2023-02-23T23:11:53.347+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T23:11:53.362+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.028 seconds
[2023-02-23T23:12:23.563+0000] {processor.py:153} INFO - Started process (PID=178) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T23:12:23.564+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T23:12:23.565+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:12:23.565+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T23:12:23.574+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:12:23.572+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.contrib.operators.gcs_check_operator import GoogleCloudStorageCheckOperator
ModuleNotFoundError: No module named 'airflow.contrib.operators.gcs_check_operator'
[2023-02-23T23:12:23.575+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T23:12:23.593+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.036 seconds
[2023-02-23T23:12:53.652+0000] {processor.py:153} INFO - Started process (PID=257) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T23:12:53.654+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T23:12:53.655+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:12:53.655+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T23:12:53.665+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:12:53.664+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.contrib.operators.gcs_check_operator import GoogleCloudStorageCheckOperator
ModuleNotFoundError: No module named 'airflow.contrib.operators.gcs_check_operator'
[2023-02-23T23:12:53.667+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T23:12:53.689+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.041 seconds
[2023-02-23T23:13:23.804+0000] {processor.py:153} INFO - Started process (PID=336) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T23:13:23.805+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T23:13:23.807+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:13:23.806+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T23:13:23.815+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:13:23.813+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.contrib.operators.gcs_check_operator import GoogleCloudStorageCheckOperator
ModuleNotFoundError: No module named 'airflow.contrib.operators.gcs_check_operator'
[2023-02-23T23:13:23.816+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T23:13:23.836+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.037 seconds
[2023-02-23T23:13:54.780+0000] {processor.py:153} INFO - Started process (PID=402) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T23:13:54.781+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T23:13:54.782+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:13:54.782+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T23:13:54.791+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:13:54.789+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.contrib.operators.gcs_check_operator import GoogleCloudStorageCheckOperator
ModuleNotFoundError: No module named 'airflow.contrib.operators.gcs_check_operator'
[2023-02-23T23:13:54.792+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T23:13:54.810+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.034 seconds
[2023-02-23T23:14:25.590+0000] {processor.py:153} INFO - Started process (PID=481) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T23:14:25.591+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T23:14:25.592+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:14:25.592+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T23:14:25.598+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:14:25.597+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.contrib.operators.gcs_check_operator import GoogleCloudStorageCheckOperator
ModuleNotFoundError: No module named 'airflow.contrib.operators.gcs_check_operator'
[2023-02-23T23:14:25.599+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T23:14:25.617+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.032 seconds
[2023-02-23T23:14:55.668+0000] {processor.py:153} INFO - Started process (PID=561) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T23:14:55.669+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T23:14:55.671+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:14:55.671+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T23:14:55.682+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:14:55.680+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.contrib.operators.gcs_check_operator import GoogleCloudStorageCheckOperator
ModuleNotFoundError: No module named 'airflow.contrib.operators.gcs_check_operator'
[2023-02-23T23:14:55.683+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T23:14:55.704+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.042 seconds
[2023-02-23T23:15:02.476+0000] {processor.py:153} INFO - Started process (PID=601) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T23:15:02.478+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T23:15:02.479+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:15:02.479+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T23:15:02.625+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:15:02.624+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GCSBucketCheckOperator
ImportError: cannot import name 'GCSBucketCheckOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-02-23T23:15:02.626+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T23:15:02.640+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.169 seconds
[2023-02-23T23:15:32.714+0000] {processor.py:153} INFO - Started process (PID=680) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T23:15:32.716+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T23:15:32.716+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:15:32.716+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T23:15:32.804+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:15:32.803+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GCSBucketCheckOperator
ImportError: cannot import name 'GCSBucketCheckOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-02-23T23:15:32.805+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T23:15:32.818+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.106 seconds
[2023-02-23T23:16:03.058+0000] {processor.py:153} INFO - Started process (PID=760) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T23:16:03.060+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T23:16:03.061+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:16:03.061+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T23:16:03.168+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:16:03.167+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GCSBucketCheckOperator
ImportError: cannot import name 'GCSBucketCheckOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-02-23T23:16:03.169+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T23:16:03.182+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.129 seconds
[2023-02-23T23:16:34.162+0000] {processor.py:153} INFO - Started process (PID=838) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T23:16:34.163+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T23:16:34.164+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:16:34.164+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T23:16:34.254+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:16:34.253+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GCSBucketCheckOperator
ImportError: cannot import name 'GCSBucketCheckOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-02-23T23:16:34.255+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T23:16:34.268+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.109 seconds
[2023-02-23T23:17:04.389+0000] {processor.py:153} INFO - Started process (PID=905) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T23:17:04.391+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T23:17:04.392+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:17:04.392+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T23:17:04.498+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:17:04.497+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GCSBucketCheckOperator
ImportError: cannot import name 'GCSBucketCheckOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-02-23T23:17:04.499+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T23:17:04.512+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.127 seconds
[2023-02-23T23:17:35.488+0000] {processor.py:153} INFO - Started process (PID=984) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T23:17:35.490+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T23:17:35.492+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:17:35.491+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T23:17:35.594+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:17:35.592+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GCSBucketCheckOperator
ImportError: cannot import name 'GCSBucketCheckOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-02-23T23:17:35.594+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T23:17:35.607+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.125 seconds
[2023-02-23T23:18:05.739+0000] {processor.py:153} INFO - Started process (PID=1064) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T23:18:05.742+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T23:18:05.743+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:18:05.743+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T23:18:05.844+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:18:05.842+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GCSBucketCheckOperator
ImportError: cannot import name 'GCSBucketCheckOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-02-23T23:18:05.845+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T23:18:05.858+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.124 seconds
[2023-02-23T23:18:36.872+0000] {processor.py:153} INFO - Started process (PID=1143) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T23:18:36.873+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T23:18:36.874+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:18:36.874+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T23:18:36.973+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:18:36.970+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GCSBucketCheckOperator
ImportError: cannot import name 'GCSBucketCheckOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-02-23T23:18:36.973+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T23:18:36.990+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.120 seconds
[2023-02-23T23:19:07.176+0000] {processor.py:153} INFO - Started process (PID=1209) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T23:19:07.178+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T23:19:07.179+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:19:07.179+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T23:19:07.277+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:19:07.275+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GCSBucketCheckOperator
ImportError: cannot import name 'GCSBucketCheckOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-02-23T23:19:07.278+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T23:19:07.291+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.117 seconds
[2023-02-23T23:19:37.480+0000] {processor.py:153} INFO - Started process (PID=1288) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T23:19:37.482+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T23:19:37.483+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:19:37.483+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T23:19:37.607+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:19:37.605+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GCSBucketCheckOperator
ImportError: cannot import name 'GCSBucketCheckOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-02-23T23:19:37.607+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T23:19:37.622+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.147 seconds
[2023-02-23T23:20:08.604+0000] {processor.py:153} INFO - Started process (PID=1367) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T23:20:08.606+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T23:20:08.608+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:20:08.608+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T23:20:08.711+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:20:08.709+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GCSBucketCheckOperator
ImportError: cannot import name 'GCSBucketCheckOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-02-23T23:20:08.712+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T23:20:08.725+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.126 seconds
[2023-02-23T23:20:38.795+0000] {processor.py:153} INFO - Started process (PID=1433) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T23:20:38.796+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T23:20:38.797+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:20:38.797+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T23:20:38.893+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:20:38.891+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GCSBucketCheckOperator
ImportError: cannot import name 'GCSBucketCheckOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-02-23T23:20:38.894+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T23:20:38.906+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.114 seconds
[2023-02-23T23:21:09.041+0000] {processor.py:153} INFO - Started process (PID=1512) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T23:21:09.043+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T23:21:09.045+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:21:09.044+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T23:21:09.148+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:21:09.146+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GCSBucketCheckOperator
ImportError: cannot import name 'GCSBucketCheckOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-02-23T23:21:09.148+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T23:21:09.161+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.125 seconds
[2023-02-23T23:33:51.955+0000] {processor.py:153} INFO - Started process (PID=34) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T23:33:51.964+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T23:33:51.965+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:33:51.965+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T23:33:52.133+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:33:52.131+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GCSBucketCheckOperator
ImportError: cannot import name 'GCSBucketCheckOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-02-23T23:33:52.134+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T23:33:52.153+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.207 seconds
[2023-02-23T23:34:22.574+0000] {processor.py:153} INFO - Started process (PID=113) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T23:34:22.575+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T23:34:22.576+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:34:22.576+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T23:34:22.700+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:34:22.698+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GCSBucketCheckOperator
ImportError: cannot import name 'GCSBucketCheckOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-02-23T23:34:22.700+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T23:34:22.712+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.141 seconds
[2023-02-23T23:34:53.645+0000] {processor.py:153} INFO - Started process (PID=179) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T23:34:53.649+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T23:34:53.650+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:34:53.650+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T23:34:53.771+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:34:53.769+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GCSBucketCheckOperator
ImportError: cannot import name 'GCSBucketCheckOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-02-23T23:34:53.771+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T23:34:53.785+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.147 seconds
[2023-02-23T23:35:18.525+0000] {processor.py:153} INFO - Started process (PID=258) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T23:35:18.526+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T23:35:18.527+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:35:18.527+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T23:35:18.623+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:35:18.622+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageCheckOperator
ImportError: cannot import name 'GoogleCloudStorageCheckOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-02-23T23:35:18.624+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T23:35:18.637+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.114 seconds
[2023-02-23T23:35:43.464+0000] {processor.py:153} INFO - Started process (PID=324) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T23:35:43.466+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T23:35:43.467+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:35:43.467+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T23:35:43.484+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:35:43.482+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.providers.google.cloud.operators import GoogleCloudStorageCheckOperator
ImportError: cannot import name 'GoogleCloudStorageCheckOperator' from 'airflow.providers.google.cloud.operators' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/__init__.py)
[2023-02-23T23:35:43.484+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T23:35:43.505+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.044 seconds
[2023-02-23T23:36:13.494+0000] {processor.py:153} INFO - Started process (PID=399) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T23:36:13.496+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T23:36:13.496+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:36:13.496+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T23:36:13.506+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:36:13.505+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.providers.google.cloud.operators import GoogleCloudStorageCheckOperator
ImportError: cannot import name 'GoogleCloudStorageCheckOperator' from 'airflow.providers.google.cloud.operators' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/__init__.py)
[2023-02-23T23:36:13.506+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T23:36:13.519+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.026 seconds
[2023-02-23T23:36:35.385+0000] {processor.py:153} INFO - Started process (PID=456) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T23:36:35.387+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T23:36:35.389+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:36:35.388+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T23:36:35.495+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:36:35.493+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageCheckOperator
ImportError: cannot import name 'GoogleCloudStorageCheckOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-02-23T23:36:35.496+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T23:36:35.511+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.129 seconds
[2023-02-23T23:36:54.554+0000] {processor.py:153} INFO - Started process (PID=483) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T23:36:54.556+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T23:36:54.557+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:36:54.557+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T23:36:54.667+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:36:54.666+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 3, in <module>
    from airflow.providers.google.cloud.operators.gcs import GCSDownloadBucketOperator
ImportError: cannot import name 'GCSDownloadBucketOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-02-23T23:36:54.668+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T23:36:54.682+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.131 seconds
[2023-02-23T23:37:14.696+0000] {processor.py:153} INFO - Started process (PID=549) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T23:37:14.698+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T23:37:14.700+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:37:14.700+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T23:37:14.808+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:37:14.807+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageCheckOperator
ImportError: cannot import name 'GoogleCloudStorageCheckOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-02-23T23:37:14.809+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T23:37:14.824+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.134 seconds
[2023-02-23T23:37:44.982+0000] {processor.py:153} INFO - Started process (PID=628) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T23:37:44.984+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T23:37:44.985+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:37:44.984+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T23:37:45.093+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:37:45.091+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageCheckOperator
ImportError: cannot import name 'GoogleCloudStorageCheckOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-02-23T23:37:45.093+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T23:37:45.108+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.129 seconds
[2023-02-23T23:38:15.166+0000] {processor.py:153} INFO - Started process (PID=693) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T23:38:15.169+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T23:38:15.170+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:38:15.170+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T23:38:15.285+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:38:15.283+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageCheckOperator
ImportError: cannot import name 'GoogleCloudStorageCheckOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-02-23T23:38:15.286+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T23:38:15.299+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.137 seconds
[2023-02-23T23:38:45.356+0000] {processor.py:153} INFO - Started process (PID=773) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T23:38:45.358+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T23:38:45.360+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:38:45.359+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T23:38:45.458+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:38:45.457+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageCheckOperator
ImportError: cannot import name 'GoogleCloudStorageCheckOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-02-23T23:38:45.459+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T23:38:45.473+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.120 seconds
[2023-02-23T23:39:16.410+0000] {processor.py:153} INFO - Started process (PID=852) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T23:39:16.412+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T23:39:16.414+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:39:16.413+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T23:39:16.513+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:39:16.511+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageCheckOperator
ImportError: cannot import name 'GoogleCloudStorageCheckOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-02-23T23:39:16.513+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T23:39:16.526+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.122 seconds
[2023-02-23T23:39:47.495+0000] {processor.py:153} INFO - Started process (PID=932) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T23:39:47.495+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T23:39:47.496+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:39:47.496+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T23:39:47.580+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:39:47.579+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageCheckOperator
ImportError: cannot import name 'GoogleCloudStorageCheckOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-02-23T23:39:47.581+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T23:39:47.594+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.102 seconds
[2023-02-23T23:40:17.834+0000] {processor.py:153} INFO - Started process (PID=998) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T23:40:17.837+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T23:40:17.838+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:40:17.838+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T23:40:17.951+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:40:17.949+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageCheckOperator
ImportError: cannot import name 'GoogleCloudStorageCheckOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-02-23T23:40:17.952+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T23:40:17.966+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.136 seconds
[2023-02-23T23:40:48.803+0000] {processor.py:153} INFO - Started process (PID=1077) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T23:40:48.805+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T23:40:48.807+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:40:48.806+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T23:40:48.903+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:40:48.902+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageCheckOperator
ImportError: cannot import name 'GoogleCloudStorageCheckOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-02-23T23:40:48.904+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T23:40:48.917+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.117 seconds
[2023-02-23T23:41:19.660+0000] {processor.py:153} INFO - Started process (PID=1156) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T23:41:19.662+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T23:41:19.662+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:41:19.662+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T23:41:19.749+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:41:19.747+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageCheckOperator
ImportError: cannot import name 'GoogleCloudStorageCheckOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-02-23T23:41:19.749+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T23:41:19.762+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.104 seconds
[2023-02-23T23:41:50.579+0000] {processor.py:153} INFO - Started process (PID=1235) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T23:41:50.581+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T23:41:50.582+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:41:50.582+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T23:41:50.670+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:41:50.669+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageCheckOperator
ImportError: cannot import name 'GoogleCloudStorageCheckOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-02-23T23:41:50.671+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T23:41:50.684+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.107 seconds
[2023-02-23T23:42:21.497+0000] {processor.py:153} INFO - Started process (PID=1300) to work on /opt/airflow/dags/update-filter.py
[2023-02-23T23:42:21.500+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/update-filter.py for tasks to queue
[2023-02-23T23:42:21.502+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:42:21.501+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/update-filter.py
[2023-02-23T23:42:21.603+0000] {logging_mixin.py:137} INFO - [2023-02-23T23:42:21.601+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/update-filter.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update-filter.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageCheckOperator
ImportError: cannot import name 'GoogleCloudStorageCheckOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-02-23T23:42:21.604+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/update-filter.py
[2023-02-23T23:42:21.636+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/update-filter.py took 0.143 seconds
